<!-- An example of how to include text based on the language. The two chunks below shows how switching the toggle in the YAML header for french allows inclusion/rejection of a paragraph. -->

```{r para-1-context-en, eval = !fr(), results = 'asis'}
cat("# Context

`r sp` (*`r sp_science`*) stock status on the West Coast of `r bc` was last assessed using data from 1996--2021 [@arf2022; @dfo2023arrowtoothSAR]. In the last assessment (reviewed in 2022; the '`r ca`'), the stock was estimated slightly below the Upper Stock Reference (USR) in the base model and close to the Limit Reference Point (LRP) under one sensitivity model with higher recruitment variation. The model also showed declining estimated spawning stock biomass, declining survey indices, and declining estimated recruitment. Due to these issues, a two-year update on the stock was requested by the Groundfish Management Unit (GMU). This two-year span was chosen since the biennial survey indexes included in the model would each have one new year of data.

The `r ca` estimated a median stock size at the beginning of 2022 (or end of 2021) of 67.95 kilotonnes (kt) with a credible interval (CI) of 56.14--83.83 kt. When divided by the estimated unfished biomass ($B_0$), the median relative biomass for 2022 was estimated to be 0.37 with a CI of 0.26--0.51. The estimated median relative biomass for 2011, was estimated to be 0.77 with a CI of 0.53--1.09. The estimated biomass declined each year from 2011--2021.

This Science Response results from the Science Response Process of October 2, 2024 on the
Stock Assessment Update of `r sp` (*`r sp_science`*) in `r bc` in 2024.
")
```

```{r para-1-context-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("# Contexte

L'état du stock de `r sp` (*`r sp_science`*) sur la côte ouest de `r bc` a été évalué pour la dernière fois en utilisant les données de 1996--2021 [@arf2022 ; @dfo2023arrowtoothSAR]. Dans la dernière évaluation (révisée en 2022 ; le '`r ca`'), le stock a été estimé légèrement en dessous de la référence supérieure du stock (RSS) dans le modèle de base et proche du point de référence limite (PRL) dans un modèle de sensibilité avec une plus grande variation du recrutement. Le modèle a également montré une baisse de la biomasse estimée du stock reproducteur, une baisse des indices d'enquête et une baisse du recrutement estimé. En raison de ces problèmes, l'unité de gestion des poissons de fond (GGPF) a demandé une mise à jour du stock sur deux ans. Cette période de deux ans a été choisie parce que les indices des relevés biennaux inclus dans le modèle auraient chacun une nouvelle année de données.

Le `r ca` a estimé une taille médiane du stock au début de 2022 (ou à la fin de 2021) de 67,95 kilotonnes (kt) avec un intervalle crédible (IC) de 56,14--83,83 kt. Lorsqu'elle est divisée par la biomasse non pêchée estimée ($B_0$), la biomasse relative médiane pour 2022 a été estimée à 0,37 avec un IC de 0,26--0,51. La biomasse relative médiane estimée pour 2011 était de 0,77 avec un IC de 0,53--1,09. La biomasse estimée a diminué chaque année entre 2011 et 2021.

Cette réponse scientifique résulte du processus de réponse scientifique du 2 octobre 2024 sur la mise à jour de l'évaluation du stock de `r sp` (*`r sp_science`*) dans `r bc` en 2024.")
```

