```{r conclusions-en, eval = !fr(), results = 'asis'}
cat("# Conclusions

The `r iscam` model used in this update had the same structure and assumptions as the model used in the `r ca`. New data added were commercial catch for 2022 and 2023, new survey index points, and new Discard CPUE index points. The growth parameters, estimated outside the `r iscam` framework, changed by a very small amount, which did not affect the model estimates.

With the addition of the new data, the relative spawning biomass trajectory from `r start_catch_yr`--2021 remained largely unchanged from the `r ca`, although the initial biomass, $B_0$, and the absolute spawning biomass values were estimated to be slightly lower in this update than in the `r ca`.

There were no large changes in fits to any index points in the four survey indices and the `r dcpue`. Three of the synoptic survey indices had one new index point added each (the `r hsmas` has a terminal year of 2003 and was not updated), and the `r dcpue` had two new index points added (2022 and 2023) since it is based on commercial catch.

The projections show medians and CIs for catches of 1 to 8 kt, in 1 kt increments (Figures \@ref(fig:fig-rel-biomass-proj) and \@ref(fig:fig-rel-biomass-proj-closeup)). The figure shows that for catch values of 1--6 kt the median of projected biomass is expected to increase to 2027. For catch values of 7--8 kt the median of projected biomass is expected to remain flat, and remain below the USR of $0.4B_0$.

Recruitment in the last four years of the model is estimated with a large degree of uncertainty (Figure \@ref(fig:fig-base-recr)). This is due to the lack of new ages being included in the model for 2022 and 2023. We expect new age composition data to be available for the next update to this assessment.

There are several harvest decision tables provided in this document (Tables \@ref(tab:decision-table-02bo)--\@ref(tab:decision-table-decreasing-biomass)) which, for 8 different catch levels from 1 kt to 8 kt, give the probabilities of the projected relative biomass being above:

1. the LRP of $0.2B_0$ (Table \@ref(tab:decision-table-02bo)),
2. the alternative USR of $0.35B_0$ (Table \@ref(tab:decision-table-035bo)),
3. the USR of $0.4B_0$ (Table \@ref(tab:decision-table-04bo)), and
4. the previous year's biomass (Table \@ref(tab:decision-table-decreasing-biomass)).

Some observations from the decision tables:

1. The probability of being above the LRP of $0.2B_0$ at the beginning of 2025 is 0.99 if the highest catch level of 8 kt is caught in 2024 (Table \@ref(tab:decision-table-02bo)),

2. The probability of being above the LRP of $0.2B_0$ at the beginning of 2027 is 0.98 if the highest catch level of 8 kt is caught each year from `r end_yr + 1` to `r end_yr + base_model$proj$num.projyrs` (Table \@ref(tab:decision-table-02bo)),

3. The probability of being above the alternative candidate USR of $0.35B_0$ at the beginning of 2025 is 0.61 if the highest catch level of 8 kt is caught in 2024 (Table \@ref(tab:decision-table-035bo)),

4. The probability of being above the alternative candidate USR of $0.35B_0$ at the beginning of 2027 is 0.60 if the highest catch level of 8 kt is caught each year from `r end_yr + 1` to `r end_yr + base_model$proj$num.projyrs` (Table \@ref(tab:decision-table-035bo)),

5. The probability of being above the candidate USR of $0.4B_0$ at the beginning of 2025 is 0.37 if the highest catch level of 8 kt is caught in 2024 (Table \@ref(tab:decision-table-04bo)),

6. The probability of being above the candidate USR of $0.4B_0$ at the beginning of 2027 is 0.42 if the highest catch level of 8 kt is caught each year from `r end_yr + 1` to `r end_yr + base_model$proj$num.projyrs` (Table \@ref(tab:decision-table-04bo)),

7. A probability of 0.5 of being above the candidate USR of $0.4B_0$ at the beginning of 2025 occurs between 2 and 4 kt of catch in 2024. A higher catch will result in the probability being less than 0.5 (Table \@ref(tab:decision-table-04bo)),

8. A probability of 0.5 of being above the candidate USR of $0.4B_0$ at the beginning of 2027 occurs between 4 and 5 kt of constant catch for each year from `r end_yr + 1` to `r end_yr + base_model$proj$num.projyrs`. A higher constant catch will result in the probability being less than 0.5 (Table \@ref(tab:decision-table-decreasing-biomass)), and

9. A probability of 0.5 of biomass increasing year-to-year for each year from `r end_yr + 1` to `r end_yr + base_model$proj$num.projyrs` occurs between 7 and 8 kt of constant catch in each year (Table \@ref(tab:decision-table-decreasing-biomass)).

This stock should be reviewed once again in three years, in September or October 2027 as a Science Response. In addition to new catch and survey index data, that update model must have new age data included for the three synoptic surveys and both fleets in the commercial fishery for the time period 2022-2026.
")
```

```{r conclusions-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("# Conclusions

Le modèle `r iscam` utilisé dans cette mise à jour avait la même structure et les mêmes hypothèses que celui utilisé dans le modèle `r ca`. Les nouvelles données ajoutées concernaient les prises commerciales de 2022 et 2023, de nouveaux indices de relevé et de nouveaux indices de CPUE rejetées. Les paramètres de croissance, estimés hors du cadre `r iscam`, ont subi une très légère modification, sans incidence sur les estimations du modèle.

Avec l'ajout des nouvelles données, la trajectoire de la biomasse reproductrice relative de `r start_catch_yr` à 2021 est restée largement inchangée par rapport au modèle `r ca`, bien que la biomasse initiale, $B_0$, et les valeurs absolues de la biomasse reproductrice aient été estimées légèrement inférieures dans cette mise à jour à celles du modèle `r ca`.

Aucune modification importante n'a été observée dans les ajustements des quatre indices de relevé et du modèle `r dcpue`. Trois des indices de l'enquête synoptique ont chacun reçu un nouvel indice (l'indice `r hsmas` a pour année terminale 2003 et n'a pas été mis à jour), et l'indice `r dcpue` a reçu deux nouveaux indice (2022 et 2023) car il est basé sur les captures commerciales.

Les projections présentent les médianes et les IC pour des captures de 1 à 8 kt, par incréments de 1 kt (Figures \@ref(fig:fig-rel-biomass-proj) et \@ref(fig:fig-rel-biomass-proj-closeup)). La figure montre que pour des captures de 1 à 6 kt, la médiane de la biomasse projetée devrait augmenter jusqu'en 2027. Pour des captures de 7 à 8 kt, la médiane de la biomasse projetée devrait rester stable et inférieure au seuil de référence de $0,4B_0$.

Le recrutement au cours des quatre dernières années du modèle est estimé avec un degré élevé d'incertitude (Figure \@ref(fig:fig-base-recr)). Cela est dû à l'absence de nouvelles données d'âge incluses dans le modèle pour 2022 et 2023. Nous prévoyons que de nouvelles données sur la composition par âge seront disponibles pour la prochaine mise à jour de cette évaluation. Ce document contient plusieurs tableaux de décision de pêche (tableaux \@ref(tab:decision-table-02bo)--\@ref(tab:decision-table-decreasing-biomass)) qui, pour huit niveaux de capture différents, de 1 kt à 8 kt, indiquent les probabilités que la biomasse relative projetée soit supérieure à :

1. le PRL de $0,2B_0$ (tableau \@ref(tab:decision-table-02bo)),
2. le RSS alternatif de $0,35B_0$ (tableau \@ref(tab:decision-table-035bo)),
3. le RSS de $0,4B_0$ (tableau \@ref(tab:decision-table-04bo)), et
4. la biomasse de l’année précédente (tableau \@ref(tab:decision-table-decreasing-biomass)).

Quelques observations issues des tables de décision :

1. La probabilité d'être au-dessus du PRL de $0,2B_0$ début 2025 est de 0,99 si le niveau de capture maximal de 8 kt est atteint en 2024 (tableau \@ref(tab:decision-table-02bo)).

2. La probabilité d'être au-dessus du LRP de $0,2B_0$ au début de 2027 est de 0,98 si le niveau de capture le plus élevé de 8 kt est capturé chaque année de `r end_yr + 1` à `r end_yr + base_model$proj$num.projyrs` (tableau \@ref(tab:decision-table-02bo)),

3. La probabilité d'être au-dessus du candidat alternatif USR de $0,35B_0$ au début de 2025 est de 0,61 si le niveau de capture le plus élevé de 8 kt est capturé en 2024 (Tableau \@ref(tab:decision-table-035bo)),

4. La probabilité d'être au-dessus du candidat alternatif USR de $0,35B_0$ au début de 2027 est de 0,60 si le niveau de capture le plus élevé de 8 kt est capturé chaque année de `r end_yr + 1` à `r end_yr + base_model$proj$num.projyrs` (tableau \@ref(tab:decision-table-035bo)),

5. La probabilité d'être au-dessus du candidat USR de $0,4B_0$ au début de 2025 est de 0,37 si le niveau de capture le plus élevé de 8 kt est capturé en 2024 (tableau \@ref(tab:decision-table-04bo)),

6. La probabilité d'être au-dessus du candidat USR de $0,4B_0$ au début de 2027 est de 0,42 si le niveau de capture le plus élevé de 8 kt est capturé chaque année de `r end_yr + 1` à `r end_yr + base_model$proj$num.projyrs` (tableau \@ref(tab:decision-table-04bo)),

7. Une probabilité de 0,5 d'être au-dessus du USR candidat de $0,4B_0$ au début de 2025 se produit entre 2 et 4 kt de captures en 2024. Une capture plus élevée entraînera une probabilité inférieure à 0,5 (tableau \@ref(tab:decision-table-04bo)),

8. Une probabilité de 0,5 d'être au-dessus du candidat USR de $0,4B_0$ au début de 2027 se produit entre 4 et 5 kt de capture constante pour chaque année de `r end_yr + 1` à `r end_yr + base_model$proj$num.projyrs`. Une prise constante plus élevée entraînera une probabilité inférieure à 0,5 (tableau \@ref(tab:decision-table-decreasing-biomass)), et

9. Une probabilité de 0,5 que la biomasse augmente d'année en année pour chaque année de `r end_yr + 1` à `r end_yr + base_model$proj$num.projyrs` se produit entre 7 et 8 kt de capture constante chaque année (tableau \@ref(tab:decision-table-decreasing-biomass)).

Ce stock devrait être réexaminé une fois de plus dans trois ans, en septembre ou octobre 2027, dans le cadre d’une réponse scientifique. En plus des nouvelles données sur les prises et les indices d'enquête, ce modèle de mise à jour doit inclure de nouvelles données sur l'âge pour les trois enquêtes synoptiques et les deux flottes de la pêche commerciale pour la période 2022-2026.

")
```