```{r intro-para-01-en, eval = !fr(), results = 'asis'}
cat("# INTRODUCTION
`r sp` (*`r sp_science`*, Family `r sp_family`, also commonly called `r sp_colloq`), is a species of flatfish that occurs in the offshore waters of British Columbia (`r bc`). `r sp` are primarily taken by the groundfish bottom trawl fishery, although they are also encountered by hook and line fisheries, particularly those targeting Pacific Halibut (*Hippoglossus stenolepis*). Prior to the introduction of freezer trawlers in the `r bc` groundfish fleet in the mid-2000s, most of the historical catch of `r sp` is understood to have been discarded at sea. Proteolysis occurs in the muscle tissue of this species a short time after it is caught, making the flesh mushy and unpalatable. In the past five years, markets have been established for fillets that have been frozen at sea as soon as possible after capture to reduce proteolysis. There is also a market for the frills. The stock was last assessed by @grandin2017, who presented an age-structured Bayesian model using the `r iscam` platform [@iscam]. This stock assessment covers the combined Pacific Marine Fisheries Commission (PMFC) major areas 3CD and 5ABCDE off the west coast of `r bc`.")
```

```{r intro-para-01-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("# INTRODUCTION
Le `r sp` (*`r sp_science`*, Famille `r sp_family`, aussi communément appelé `r sp_colloq`), est une espèce de poisson plat que l'on trouve dans les eaux du large de la Colombie Britannique (`r bc`). Les `r sp` sont principalement capturés par la pêche au chalut de fond des poissons de fond, bien qu'ils soient également rencontrés par les pêcheries à la ligne et à l'hameçon, en particulier celles ciblant le flétan du Pacifique (*Hippoglossus stenolepis*). Avant l'introduction de chalutiers congélateurs dans la flotte de pêche au poisson de fond `r bc` au milieu des années 2000, la plupart des prises historiques de `r sp` étaient rejetées en mer. La protéolyse se produit dans le tissu musculaire de cette espèce peu de temps après la capture, ce qui rend la chair pâteuse et peu appétissante. Au cours des cinq dernières années, des marchés ont été créés pour les filets qui ont été congelés en mer dès que possible après la capture afin de réduire la protéolyse. Il existe également un marché pour les fioritures. La dernière évaluation du stock a été réalisée par @grandin2017, qui a présenté un modèle bayésien structuré par âge utilisant la plateforme `r iscam` [@iscam]. Cette évaluation du stock couvre les zones principales combinées 3CD et 5ABCDE de la Commission des pêches maritimes du Pacifique (PMFC) au large de la côte ouest de la `r bc`.")
```

```{r intro-para-02-en, eval = !fr(), results = 'asis'}
cat("## PURPOSE OF DOCUMENT
`r sp` is managed as a coastwide stock in `r bc` with the majority of the catch coming from Pacific Marine Fisheries Commission (PMFC) major areas 3CD; `r wcvi`, 5AB; `r qcs` and 5CD; `r hs` (Figures \@ref(fig:fig-catch-spatial)--\@ref(fig:fig-trawl-footprint), Table \@ref(tab:area-catch-table)). The Strait of Georgia (management area 4B) is not included in this stock assessment. The Total Allowable Catch (TAC) has been 5,000 t since February 21, 2020. The TAC was 15,000 t for many years prior to the reduction in 2020. February 21 is the start date for the groundfish trawl fishery each year.")
```
```{r intro-para-02-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## OBJECTIF DU DOCUMENT
Le `r sp` est géré comme un stock côtier en `r bc`, la majorité des captures provenant des principales zones de la Commission des pêches maritimes du Pacifique (PMFC) 3CD; `r wcvi`, 5AB; `r qcs` et 5CD; `r hs` (Figures \@ref(fig:fig-catch-spatial)--\@ref(fig:fig-trawl-footprint), Tableau \@ref(tab:area-catch-table)). Le détroit de Géorgie (zone de gestion 4B) n'est pas inclus dans cette évaluation du stock. Le total admissible des captures (TAC) est de 5 000 tonnes depuis le 21 février 2020. Le TAC a été de 15 000 t pendant de nombreuses années avant la réduction de 2020. Le 21 février est la date de début de la pêche au chalut du poisson de fond chaque année.")
```

```{r intro-para-03-en, eval = !fr(), results = 'asis'}
cat("The purpose of this stock assessment is to update management advice for `r sp` stocks in `r bc` as requested by the Pacific Groundfish Management Unit (GMU). This assessment identifies reference points for `r sp` that are consistent with the DFO Decision-Making Framework Incorporating the Precautionary Approach [@dfo2009] and characterizes stock status relative to these reference points using a Bayesian, age-structured stock assessment model. Management advice is provided in the form of decision tables, which forecast the impacts of a range of harvest levels on `r sp` stock status relative to these reference points.")
```
```{r intro-para-03-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("L'objectif de cette évaluation de stock est d'actualiser l'avis de gestion pour les stocks de `r sp` en `r bc`, à la demande de l'Unité de gestion des poissons de fond du Pacifique (GMU). Cette évaluation identifie les points de référence pour `r sp` qui sont conformes au cadre décisionnel du MPO intégrant l'approche de précaution [@dfo2009] et caractérise l'état du stock par rapport à ces points de référence à l'aide d'un modèle bayésien d'évaluation des stocks structuré en fonction de l'âge. L'avis de gestion est fourni sous la forme de tables de décision, qui prévoient les impacts d'une gamme de niveaux d'exploitation sur l'état du stock `r sp` par rapport à ces points de référence.")
```

```{r intro-para-04-en, eval = !fr(), results = 'asis'}
cat("## BIOLOGICAL BACKGROUND
`r sp` are distinguished by their large mouth and arrow-shaped teeth, for which the species is named. Their distribution ranges from Baja California to the eastern Bering Sea [@hart1973]. In `r bc`, the species inhabits depths from 50--900 m [@arf2001].")
```

```{r intro-para-04-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## CONTEXTE BIOLOGIQUE
`r sp` se distinguent par leur grande bouche et leurs dents en forme de flèche, d'où le nom de l'espèce. Leur répartition s'étend de la Basse-Californie à l'est de la mer de Béring [@hart1973]. En `r bc`, l'espèce habite à des profondeurs allant de 50 à 900 m [@arf2001].")
```

```{r intro-para-05-en, eval = !fr(), results = 'asis'}
cat("`r sp` exhibit sexual dimorphism. After sexual maturity, females grow faster than males and reach a larger maximum size (Appendix \@ref(app:bio-data-appendix), Figure \@ref(fig:fig-vb)). Theoretical maximum length, $L_{\infty}$, is estimated to be `r round(mat_fit$female[1], 1)` cm for females and `r round(mat_fit$male[1], 1)` cm for males in `r bc` although the maximum sizes that have been observed are `r round(max(filter(all_length_samples, sex == 2)$length, na.rm = T), 1)` cm for females and `r round(max(filter(all_length_samples, sex == 1)$length, na.rm = T), 1)` cm for males (Figures \@ref(fig:fig-lengths) and \@ref(fig:fig-vb)). Age-at-50%-maturity for females is thought to occur around age `r round(mat_fit$female[6], 1)` y for females and `r round(mat_fit$male[6], 1)` y for males (Figure \@ref(fig:fig-mat)). The maximum observed age is `r round(max(filter(all_age_samples, sex == 2)$age, na.rm = T), 1)` y for females and `r round(max(filter(all_age_samples, sex == 1)$age, na.rm = T), 1)` y for males. There were few observations of fish over 20 y in the dataset, and this assessment assumes a plus group of 20 y (Figure \@ref(fig:fig-ages)).")
```

```{r intro-para-05-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("`r sp` présentent un dimorphisme sexuel. Après la maturité sexuelle, les femelles grandissent plus vite que les mâles et atteignent une taille maximale plus importante (Annexe \@ref(app:bio-data-appendix), Figure \@ref(fig:fig-vb)). La longueur maximale théorique, $L_{\infty}$, est estimée à `r round(mat_fit$female[1], 1)` cm pour les femelles et `r round(mat_fit$male[1], 1)` cm pour les mâles en `r bc` bien que les tailles maximales qui ont été observées soient `r round(max(filter(all_length_samples, sex == 2)$length, na.rm = T), 1)` cm pour les femelles et `r round(max(filter(all_length_samples, sex == 1)$length, na.rm = T), 1)` cm pour les mâles (figures \@ref(fig:fig-lengths) et \@ref(fig:fig-vb)). On pense que l'âge à 50 % de la maturité pour les femelles se situe autour de `r round(mat_fit$female[6], 1)` y pour les femelles et `r round(mat_fit$male[6], 1)` y pour les mâles (figure \@ref(fig:fig-mat)). L'âge maximum observé est `r round(max(filter(all_age_samples, sex == 2)$age, na.rm = T), 1)` y pour les femelles et `r round(max(filter(all_age_samples, sex == 1)$age, na.rm = T), 1)` y pour les mâles. Il y avait peu d'observations de poissons de plus de 20 ans dans le jeu de données, et cette évaluation suppose un groupe plus de 20 ans (Figure \@ref(fig:fig-ages)).")
```

```{r intro-para-06-en, eval = !fr(), results = 'asis'}
cat("`r sp` are batch spawners with peak spawning occurring at depths deeper than 350 m in the fall and winter months, although the timing of spawning may vary inter-annually [@arf1995]. The species produces pelagic eggs, followed by a pelagic larval stage that may last several months [@arf1995]. Fecundity of this species is poorly understood [@dicosimo1998]. One- and two-year-old fish occupy shallower depths than adults, but by the age of three or four years old, they are generally found in deeper water with adults [@arf2001]. `r sp` appear to occupy separate spawning (winter) and feeding (summer) areas, and undergo seasonal bathymetric movement from shallower to deeper water in the fall and winter [@arf2001].")
```
```{r intro-para-06-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("`r sp` sont des reproducteurs discontinus dont le pic de frai se produit à des profondeurs supérieures à 350 m pendant les mois d'automne et d'hiver, bien que le moment du frai puisse varier d'une année à l'autre [@arf1995]. L'espèce produit des œufs pélagiques, suivis d'un stade larvaire pélagique qui peut durer plusieurs mois [@arf1995]. La fécondité de cette espèce est mal connue [@dicosimo1998]. Les poissons âgés d'un ou deux ans occupent des profondeurs plus faibles que les adultes, mais à l'âge de trois ou quatre ans, on les trouve généralement dans des eaux plus profondes avec les adultes [@arf2001]. Les `r sp` semblent occuper des zones de frai (hiver) et d'alimentation (été) séparées, et subissent des mouvements bathymétriques saisonniers des eaux peu profondes vers les eaux plus profondes en automne et en hiver [@arf2001].")
```

```{r intro-para-07-en, eval = !fr(), results = 'asis'}
cat("`r sp` have a diet comprised of zooplankton, fish, and benthic invertebrates. Juveniles feed primarily on mobile prey such as euphausiids, cumaceans, carideans, and amphipods. Adults are more piscivorous and cannibalistic, feeding on Pacific Herring (*Clupea pallasii*), juvenile Walleye Pollock (*Theragra chalcogramma*), and Pacific Sandlance (*Ammodytes hexapterus*), among other species [@fargo1981; @yang1993].")
```

```{r intro-para-07-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("Le régime alimentaire des `r sp` se compose de zooplancton, de poissons et d'invertébrés benthiques. Les juvéniles se nourrissent principalement de proies mobiles telles que les euphausiacés, les cumacés, les carides et les amphipodes. Les adultes sont plus piscivores et cannibales, se nourrissant de harengs du Pacifique (*Clupea pallasii*), de dauphins juvéniles (*Theragra chalcogramma*) et de lançons du Pacifique (*Ammodytes hexapterus*), entre autres espèces [@fargo1981; @yang1993].")
```

```{r intro-para-08-en, eval = !fr(), results = 'asis'}
cat("## FISHERY AND MANAGEMENT HISTORY {#intro-management}
Prior to 2006 there were no limits on the amount of `r sp` that could be caught. In 2006 a TAC of 15,000 t was established and it remained at this level until 2017. In 2017, the TAC was increased to 17,500 t and remained there for two years until it was reduced to 14,000~t in 2019 as a precautionary measure to address concerns raised by the commercial trawl fleet about their observations of reduced abundance in the `r sp` fishery. In 2020 the TAC was decreased to 5,000 t to address industry concerns regarding declining `r sp` abundance on traditional fishing grounds [@dfomemo2020].

### FISHERY MANAGEMENT IMPACTS ON CATCH AND REPORTING {#test-fishery}
The increase in catch seen from 2010--2014 (Figure \@ref(fig:fig-catch)) was due to new market opportunities. There has been an overall decline in annual catches since 2017, with a particularly large decrease occurring in 2019 (Figure \@ref(fig:fig-catch)) and continuing through 2021. The large decrease is due to the quota reduction which was based on survey abundance index and commercial CPUE declines.

Prior to the introduction of freezer trawlers, most of the historical catch of `r sp` is understood to have been released at sea in unknown quantities due to proteolysis of the flesh if catches were not landed and frozen quickly after capture. Before the introduction of 100% at-sea observer coverage in the `r bc` groundfish fleets in 1996, reporting of `r sp` discards in fishery logbooks was mandatory, but since `r sp` were not given a TAC until 2005, there was little incentive for skippers to record discards accurately until at-sea observers were present aboard vessels starting in 1996. The quantity of discards in the pre-1996 period is highly uncertain and no catch reconstruction prior to 1996 could be made for this assessment. Figure \@ref(fig:fig-trawl-footprint) shows the boundaries of the commercial trawl sector (for all species) with the Synoptic surveys overlaid.

U.S. and foreign catches were not accounted for in this assessment.")
```
```{r intro-para-08-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## HISTORIQUE DE LA PÊCHE ET DE LA GESTION {#intro-management}
Avant 2006, il n'y avait aucune limite à la quantité de `r sp` pouvant être capturée. En 2006, un TAC de 15 000 tonnes a été établi et est resté à ce niveau jusqu'en 2017. En 2017, le TAC a été augmenté à 17 500 t et est resté à ce niveau pendant deux ans jusqu'à ce qu'il soit réduit à 14 000~t en 2019 comme mesure de précaution pour répondre aux inquiétudes soulevées par la flotte de chalutiers commerciaux concernant la réduction observée de l'abondance de `r sp`. En 2020, le TAC a été ramené à 5 000 tonnes pour répondre aux préoccupations du secteur concernant la diminution de l'abondance du `r sp` sur les lieux de pêche traditionnels [@dfomemo2020].

### IMPACTS DE LA GESTION DE LA PÊCHE SUR LA PRISE ET LA DÉCLARATION {#test-fishery}
L'augmentation des captures observée entre 2010 et 2014 (figure \@ref(fig:fig-catch)) était due à de nouvelles opportunités de marché. Depuis 2017, on observe une baisse générale des captures annuelles, avec une diminution particulièrement importante en 2019 (Figure \@ref(fig:fig-catch)) qui se poursuivra jusqu'en 2021. Cette forte baisse est due à la réduction des quotas, qui était basée sur les baisses de l'indice d'abondance des relevés et de la CPUE commerciale.

Avant l'introduction des chalutiers congélateurs, la plupart des captures historiques de `r sp` ont été rejetées en mer en quantités inconnues en raison de la protéolyse de la chair si les captures n'étaient pas débarquées et congelées rapidement après la capture. Avant l'introduction d'une couverture à 100 % par des observateurs en mer dans les flottes de poissons de fond `r bc` en 1996, la déclaration des rejets de `r sp` dans les journaux de bord était obligatoire, mais comme les `r sp` n'ont pas reçu de TAC avant 2005, les patrons de pêche n'étaient guère incités à enregistrer les rejets avec précision jusqu'à ce que des observateurs en mer soient présents à bord des navires à partir de 1996. La quantité de rejets au cours de la période antérieure à 1996 est très incertaine et aucune reconstitution des captures antérieures à 1996 n'a pu être effectuée aux fins de la présente évaluation. La figure \@ref(fig:fig-trawl-footprint) montre les limites du secteur du chalutage commercial (pour toutes les espèces) avec les relevés synoptiques superposés.

Les prises américaines et étrangères n'ont pas été prises en compte dans cette évaluation.")
```

\clearpage
