# Introduction

```{r intro-para-01-en, eval = !fr(), results = 'asis'}
b(sp, " (*", sp_science, "*, Family ", sp_family, "), also commonly called ", sp_colloq, ", is a species of flatfish that occurs in the offshore waters of ", bc, ". ", sp, " are primarily taken by the groundfish bottom trawl fishery, although they are also encountered by hook and line fisheries, particularly those targeting Pacific Halibut (*Hippoglossus stenolepis*). Prior to the introduction of freezer trawlers in the ", bc, " groundfish fleet in the mid-2000s, most of the historical catch of ", sp, " is understood to have been discarded at sea. Proteolysis occurs in the muscle tissue of this species a short time after it is caught, making the flesh mushy and unpalatable. In the past five years, Asian markets have been established for fillets that have been frozen at sea as soon as possible after capture to reduce proteolysis. There is also an Asian market for the frills. The stock was last assessed by @grandin2017, who presented an age-structured Bayesian model using the iSCAM platform. This stock assessment covers the combined Pacific Marine Fisheries Commission (PMFC) major areas 3CD and 5ABCDE off the west coast of ", bc, ".")
```

```{r intro-para-01-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-01-en>>
```

```{r intro-para-02-en, eval = !fr(), results = 'asis'}
b("## Purpose of document

", sp, " is managed as a coastwide stock in ", bc, ", with the majority of the catch coming from Pacific Marine Fisheries Commission (PMFC) major areas 3CD; ", wcvi, ", 5AB; ", qcs, " and 5CD; ", hs, " (Figures XX and XX, Table XX). The Strait of Georgia (management area 4B) is not included in this stock assessment. The 2020 Total Allowable Catch (TAC) was 4,000 metric tonnes, reduced from 15,000 t in March of 2020.")
```
```{r intro-para-02-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-02-en>>
```

```{r intro-para-03-en, eval = !fr(), results = 'asis'}
b("The purpose of this stock assessment is to update management advice for ", sp, " stocks in ", bc, ", as requested by the Pacific Groundfish Management Unit (GMU). This assessment identifies reference points for ", sp, " that are consistent with the DFO Decision-making Framework Incorporating the Precautionary Approach [@dfo2009] and characterizes stock status relative to these reference points, using a Bayesian, age-structured stock assessment model. Management advice is provided in the form of decision tables which forecast the impacts of a range of harvest levels on ", sp, " stock status relative to these reference points.")
```
```{r intro-para-03-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-03-en>>
```

```{r intro-para-04-en, eval = !fr(), results = 'asis'}
b("## Biological background
  
", sp, " are distinguished by their large mouth and arrow-shaped teeth, for which the species is named [@hart1973]. Their distribution ranges from Baja California to the eastern Bering Sea (@hart1973). In ", bc, ", the species inhabits depths from 50--900 m (@arf2001).")
```
```{r intro-para-04-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-04-en>>
```

```{r intro-para-05-en, eval = !fr(), results = 'asis'}
b(sp, " exhibit sexual dimorphism. After sexual maturity, females grow faster than males and reach a larger maximum size (Appendix XX, Figure XX). Theoretical maximum length, $L_{\\infty}$, is estimated to be XX cm for females and XX cm for males in ", bc, ", although the maximum sizes which have been observed are XX cm for females and XX cm for males (Figure XX). Age-at-50%-maturity for females is thought to occur around age XX y for females and XX y for males. The maximum observed age is XX y for females and XX y for males. There were few observations of fish over 20 y in the dataset, and this assessment assumes a plus group of 20 y (Figure XX).")
```
```{r intro-para-05-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-05-en>>
```

```{r intro-para-06-en, eval = !fr(), results = 'asis'}
b(sp, " are batch spawners with peak spawning occurring at depths deeper than 350 m in the fall and winter months, although the timing of spawning may vary inter-annually [@arf1995]. The species produces pelagic eggs, followed by a pelagic larval stage that may last several months [@arf1995]. Fecundity of this species is poorly understood [@dicosimo1998]. One and two year old fish occupy shallower depths than adults, but by the age of three or four years old, they are generally found in deeper water with adults [@arf2001]. ", sp, " appear to occupy separate spawning (winter) and feeding (summer) areas, and undergo seasonal bathymetric movement from shallower to deeper water in the fall and winter [@arf2001].")
```
```{r intro-para-06-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-06-en>>
```

```{r intro-para-07-en, eval = !fr(), results = 'asis'}
b("Juvenile ", sp, " feed primarily on mobile prey such as cumaceans, carideans and amphipods. Adults are piscivorous and cannibalistic, feeding on Pacific Herring (*Clupea pallasii*), juvenile Walleye Pollock (*Theragra chalcogramma*) and Pacific Sandlance (*Ammodytes hexapterus*), among other species [@fargo1981].")
```
```{r intro-para-07-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-07-en>>
```
```{r intro-para-08-en, eval = !fr(), results = 'asis'}
b("## Fishery and management history
  
", sp, " has been managed on a status-quo basis in recent years, with an annual allocation of 15,000 t for the groundfish trawl fleet since 2006. Before that time, there were no limits on catches or discards of ", sp, ". The areas of high CPUE in Dixon Entrance seen in Figure \\@ref(fig:cpue) are mainly from this test fishery.")
```
```{r intro-para-08-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<intro-para-08-en>>
```

\clearpage