```{r bridging-para-01-en, eval = !fr(), results = 'asis'}
cat("# Model bridging {#bridging}
A set of bridging models was run to determine the effects of incremental model modifications while moving from the single-sex, single-fleet `r la` model to the split-sex, two-fleet model used in this assessment.

The base model from the `r la` [@grandin2017] was run with the newest version of the iSCAM code and the original data files. The parameter estimates, reference points, estimated trajectories, index fits, and age comp fits were determined to be identical. The 2015 model was a female-only catch-at-age model with 4 indices of abundance which included the three Synoptic surveys and the Hecate Strait Multispecies assemblage survey.

The Technical Working Group (TWG) agreed that the model should be split-sex, based on the sexual dimorphism obseved in the age and legnth data for this species and there being 8 more years of data since the `r la`, which allowed for an larger number of age proportion specimens for each sex.

All bridge models were run using MCMC with a chain length of `r f(mcmc_chain_length)`, a sample frequency of `r f(mcmc_sample_freq)`, giving `r f(mcmc_num_samples)` samples, which were then burned in by `r f(mcmc_burn_in)` giving a total of `r f(mcmc_actual_samples)` samples actually used.
")
```
```{r bridging-para-01-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<bridging-para-01-en>>
```

```{r bridging-para-02-en, eval = !fr(), results = 'asis'}
cat("Each model in this list is based on the previous one with only one change made so incremental changes can be tracked.

1. 2015 Base model [@grandin2017].
1. Extracted the data for the 2015 model using the [gfplot](https://github.com/pbs-assess/gfplot) package, which has been used in several assessments and in the [gfsynopsis](https://github.com/pbs-assess/gfsynopsis) report.
1. Using the same data extraction methods as in the previous step, appended data up to and including 2021. The proportion female was changed in this step from 70% to `r total_prop_female`%.
1. Added the `r wchgs` index and age comps. This was tried to determine if the additional survey years since 2015 contributed anything to the model fit.
1. Switched the age comp likelihood from Multivariate Normal Logistic to the saturating parameterization of the Dirichlet-Multinomial [@thorson2016]. This was done to avoid manually reweighting the age proportions for each different model run, and instead have the weighting paramaterized in the model.
1. Changed the model from one to two commercial fleets. This splits the commercial trawl catch into catch from Freezer Trawlers and Shoreside fleets. This was done by recommendation of the TWG, since the large freezer trawlers may fish differently and have different selectivity than the shoreside vessels.
1. Added the Discard CPUE index. This was suggested by the Technical Working Group (TWG) and is an index for vessels that were not fishing for `r sp` and therefore were discarding all that they caught incidentally. The selectivity could not be estimated for this index since there are no age composition data for it, so its selectivity was fixed to values representative of other estimated selectivities from other gears. See Appendix \@ref(app:dcpue) for details on how this index was genereated.
1. Converted the model from female-only to a split-sex model. In this model, the two natural mortality parameters for male and female were fixed. In the previous models, the female natural mortality was estimated. This was done due to poor diagnostics when the parameters were estimated, and to follow what was done in recent Gulf of Alaska assessments (@spies2019).
1. Changed fishing year to Feb. 21 - Feb. 20, which is the range currently used by fisheries management for the fishing year.
1. Removed the `r wchgs` index and age comps. It was not contributing anything to the assessment and the estimated selectivities were not viable due to too few samples. Its removal was suggested by the Technical Working Group (TWG).
1. Fixed both male and female natural morality parameters. The estimated values were quite low for this species based on previous assessments in the area (@grandin2017, @spies2019).
1. Added time-varying selectivity for the `r qcs`. Three year blocks were added in an attempt to improve the index fit for the survey.
1. Enable estimation of total variance ($\vartheta^2$).

")
```

```{r bridging-para-02-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<bridging-para-02-en>>
```

```{r bridging-para-03-en, eval = !fr(), results = 'asis'}
cat("
**Bridge models group 1 (models 1-4)**
Figure \@ref(fig:bridge-biomass-group1) shows the absolute and relative spawning biomass for the first four bridging models in the list above (list items 1-4). Changing the data extraction method for all data up to 2014 does not have much effect, with only a small difference in 2015 absolute biomass and a very small difference in 2015 relative biomass. Small changes in data are mainly due to changes in survey indices, which are caused by survey blocks being removed from the entire survey series. These blocks were found to be unfishable or inappropriate for the index in the surveys since 2014 and were removed from the entire series, changing the historical indices slightly from those included in the `r la`.

Adding the data from 2015--`r base_model$dat$end.yr` causes a large effect in the model (Figure \@ref(fig:bridge-biomass-group1)). The biomass begins dropping more quickly as far back as 2002, with a relatively steep drop from 2010--2020. This decline in the biomass is caused mainly by the declining indices of abundance in that time period. From 2021--2022 the model shows the beginnings of an upward trend.

Adding the `r wchgs` age compositions and index into the model has a scaling effect in the earlier part of the trajectory, but both absolute and relative biomasses are near identical for 2022 (Figure \@ref(fig:bridge-biomass-group1)).

Credible intervals becom much narrower with the addition of the 2015--2021 data.

")
```

```{r bridging-para-03-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<bridging-para-03-en>>
```

```{r bridging-para-04-en, eval = !fr(), results = 'asis'}
cat("**Brdige models group 2 (models 5-8)**
Figure \@ref(fig:bridge-biomass-group2) shows the absolute and relative spawning biomass for the second group of four bridging models (list items 5-8). Changing the age data weighting to a parameterized form, the saturated Dirichlet Multinomial (DM) [@thorson2016], causes a drop in absolute biomass and $B_0$. The $B_0$ median for the first model in Figure \@ref(fig:bridge-biomass-group2), when compared to the $B_0$ median for the last model in Figure \@ref(fig:bridge-biomass-group1) shows there is a decline from `r bridge_1_4_bo[1]` thousand t to `r bridge_2_1_bo[1]` thousand t. However, the biomass estimate is also scaled down, so the `r bridge_1_4_depl[3]` relative biomass only drops a small amount (`r bridge_1_4_depl[1]` to `r bridge_2_1_depl[1]`).
    
The commercial trawl was split into two fleets, the `r base_model$dat$fleet_gear_names[1]` and `r base_model$dat$fleet_gear_names[2]` fleets. This changed the model internals significantly but had negligible effect on the biomass and relative biomass trajectories (Figure \@ref(fig:bridge-biomass-group2)).

Adding the `r dcpue` (DCPUE) to the model had almost no effect to neither the output biomass nor the $B_0$ estimates. It did reduce the credible interval on the top end in the absolute sense (Figure \@ref(fig:bridge-biomass-group2), left panel). This reduction in credible interval would likely be due to the good fit to the index (Figure \@ref(fig:bridge-index-group2)). The details of the DCPUE are given in Appendix \@ref(app:dcpue).

The next step in the bridging was to convert the model into split-sex. All previous bridge models were female-only and this step involved significant modifications to the iSCAM model code. This change caused a drop in final-year biomass and relative biomass, and some overall scaling up of the historical relative biomass trajectory (Figure \@ref(fig:bridge-biomass-group2)). The switch to a split-sex model did have an impact on the index fit to the `r qcs`; the first few years' fit was closer to the inital index point which was significantly lower than the rest in the series (Figure \@ref(fig:bridge-index-group2)). This is likely a selectivity issue caused by a higher proporionate amount of females per age group in the first few survey years (2003 and 2005) followed by no age data for that survey from 2006--2010 (Figure \@ref(fig:fig-ages)).

")
```

```{r bridging-para-04-fr, eval = fr(), results = 'asis', needs_trans = TRUE}
<<bridging-para-04-en>>
```

```{r bridging-para-05-en, eval = !fr(), results = 'asis'}
cat("**Bridge models group 3 (models 9-13)**
The biomass plots for the final group of bridging models (list items 9-13) can be found in Figure \@ref(fig:bridge-biomass-group3). For the first of these models, the fishing year was changed from what it was in the `r la`, January 1--December 31 to February 21--February 20. This change was made to reflect the start date for the fishery each year in Canada (February 21). The effect of this is the median $B_0$ dropping a small amount from `r bridge_1_4_bo[1]` to `r bridge_2_1_bo[1]` thousand t, and the `r bridge_2_4_bo[3]` relative biomass being reduced from `r bridge_1_4_depl[1]` to `r bridge_2_1_depl[1]`. The credible interval of the absolute biomass is reduced by this change in fishery timing from `r bridge_1_4_sbt[2]` to `r bridge_2_1_sbt[2]`. However, the credible interval on the relative biomass is still very similar to the previous model in group 2, `r bridge_1_4_depl[2]` for the previous model vs. `r bridge_2_1_depl[2]` for the one with the fishery timing change (Figure \@ref(fig:bridge-biomass-group3)).
    
The `r wchgs` was removed, as it was in the `r la`, as it had very little effect on the biomass and some troubling selectivity estimates (Figure \@ref(fig:bridge-biomass-group3)).

The natural mortalities coming from the model at this point were `r bridge_3_2_m_male[1]`, for males and `r bridge_3_2_m_female[1]` for females with credible intervals of `r bridge_3_2_m_male[2]` and `r bridge_3_2_m_female[2]` respectively. While the value for males made sense, the female value was much lower than what was expected (Figure \@ref(fig:bridge-biomass-group3)). The `r la` estimated a value of 0.314 for female natural mortality and the Gulf of Alaska (GOA) assessment use a fixed value of 0.35 [@spies2019]. We decided to fix the natural mortalities at the same values as the GOA assessment, which are 0.2 for males and 0.35 for females.

The fit to the `r qcs` index was found to be unacceptable with the previous model, so attempts were made to improve it. The only modification that yielded a better fit without producing unrealistic selectivity parameter estimates was to employ time-varying selectivity for the `r qcs`. Selectivities for two year blocks were estimated, `r tv_block1` and `r tv_block2`. Other year block ranges, addition of more year blocks, and addition of TV selectivity to other survey indices were examined but none performed as well as the two-block `r qcs` configuration, so that was settled on for the base model (Figure \@ref(fig:bridge-biomass-group3)).

")
```