```{r dynamic-bo-en, eval = !fr(), results = 'asis'}
cat("## DYNAMIC $B_0$ {#dynamic-bo}

A dynamic $B_0$ was calculated in R using the mean parameter values and expanded to include the two-fleet, two-sex catch-at-age model. The fishing mortality was set to zero and all mean parameter estimates were included. Figure \@ref(fig:fig-dynamic-b-zero) shows the estimated biomass trajectories for this case.

The biomass calculated using a dynamic $B_0$ approach is significantly higher for all years than using a non-dynamic $B_0$ produces.

This work was done at the request of the review meeting participants, after the initial draft of this stock assessment.")
```

```{r dynamic-bo-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## DYNAMIQUE $B_0$ {#dynamic-bo}

Un $B_0$ dynamique a été calculé dans R à l'aide des valeurs moyennes des paramètres et étendu pour inclure le modèle de capture par âge à deux flottes et deux sexes. La mortalité par pêche a été fixée à zéro et toutes les estimations moyennes des paramètres ont été incluses. La figure \@ref(fig:fig-dynamic-b-zero) montre les trajectoires de biomasse estimées pour ce cas.

La biomasse calculée en utilisant une approche dynamique $B_0$ est significativement plus élevée pour toutes les années qu'en utilisant une approche non dynamique $B_0$.

Ce travail a été réalisé à la demande des participants à la réunion d'examen, après la première version de cette évaluation du stock.")
```