```{r scam-model-description-en, eval = !fr(), results = 'asis'}
cat("## STATISTICAL CATCH-AT-AGE MODEL {#scam-model}
### Model Description {#scam-model-desc}

A two-sex, Bayesian statistical catch-at-age model was applied to assess the coastwide stock status of `r sp`. The model is based on the Integrated Statistical Catch Age Model (`r iscam`) framework, @martell2011. Full model details are provided in Appendix \@ref(app:model-desc).

We define a base model with fixed and estimated parameters described in Table \@ref(tab:param-settings-table). A total of `r num_params` model parameters were estimated by the base model (Table \@ref(tab:param-settings-table) shows most of these). The model estimated time series of log recruitment anomalies and log fishing mortality rates; and time-invariant values of unfished recruitment, steepness of the Beverton-Holt stock-recruit relationship, natural mortality, average recruitment, and logistic selectivity parameters for the two commercial fisheries and the four synoptic surveys. Prior probability distributions for the base model are shown in Table \@ref(tab:param-settings-table) and Figure \@ref(fig:fig-base-priors-posts) and described in Section \@ref(scam-model-priors). Model sensitivity to fixed parameters and to assumed prior probability distributions are presented in Section \@ref(sens-analyses).

The model was conditioned on observed catch data (`r ct_start_yr`--`r ct_end_yr`), which were assumed to be known without error. The model was fit to four survey indices of abundance, the Discard CPUE index, and to age composition data from the two commercial fisheries, and three synoptic surveys. Biological parameters determining weight-at-age and maturity-at-age schedules were estimated independently (Appendix \@ref(app:bio-data-appendix)) and input into the assessment model as fixed parameters that remained constant over time (Table \@ref(tab:growth-params-table)).

Survey biomass indices were treated as relative abundance indices that are directly proportional to the survey vulnerable biomass at the beginning of each year. Observation errors in relative abundance indices were assumed to be log-normally distributed. The catchability parameter $q_k$ was estimated for each index $k$. Prior probability distributions for $\ln(q_k)$ are described in Section \@ref(scam-model-priors).

Age-composition observations were assumed drawn from a Dirichlet-multinomial distribution. It was assumed ages were read without error.

Selectivity-at-age for the trawl fisheries, four surveys, and Discard CPUE index was modelled using a two-parameter logistic function with asymptote at 1. Age-at-50%-vulnerability ($\hat{a}_k$) and the standard deviation of the logistic selectivity curve ($\hat{\gamma}_k$) for each gear $k$ were estimated for the trawl fisheries and the three synoptic surveys. No age composition data were available for the `r hsmas` and `r dcpue` so selectivity was fixed with $\hat{a}_k$ = `r f(base_model$ctl$sel[2, 4])` and $\hat{\gamma}_k$ = `r f(base_model$ctl$sel[3, 4], 1)`, similar to estimated values for the other gears. Additional sensitivity runs not included in this assessment document indicated that there was little model sensitivity to this assumption.

Variance components of the model were partitioned into observation and process errors. The key parameter is the total variance (i.e., $\vartheta^2$, total precision). The total variance is partitioned into observation and process error components by the model parameter $\rho$, which represents the proportion of the total variance that is due to observation error [@punt1999; @deriso2007]. The total variance is partitioned into observation errors ($\sigma$) and process errors ($\tau$) using Eq. \@ref(eq:df17) from Appendix \@ref(app:model-desc). The parameters $\vartheta^2$ and $\rho$ were fixed in the current assessment (Table \@ref(tab:param-settings-table)) at values that gave $\sigma = 0.2$ and $\tau = 0.8$. See Section \@ref(sens-sigma) for sensitivity analyses to this assumption. See Appendix \@ref(app:model-desc) for further details on the treatment of variance in this assessment.")
```

```{r scam-model-description-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## Modèle statistique de capture à l'âge {#scam-model}
### Description du modèle {#scam-model-desc}

Un modèle statistique de capture en fonction de l'âge, bayésien et à deux sexes, a été appliqué pour évaluer l'état du stock de `r sp` sur l'ensemble de la côte. Le modèle est basé sur le cadre du modèle statistique intégré de capture par âge (`r iscam`), @martell2011. Les détails complets du modèle sont fournis dans l'annexe \@ref(app:model-desc).

Nous définissons un modèle de base avec des paramètres fixes et estimés décrits dans le tableau \@ref(tab:param-settings-table). Un total de `r num_params` paramètres du modèle ont été estimés par le modèle de base (le tableau \@ref(tab:param-settings-table) montre la plupart d'entre eux). Le modèle a estimé des séries temporelles de logarithmes d'anomalies de recrutement et de logarithmes de taux de mortalité par pêche, ainsi que des valeurs invariantes dans le temps du recrutement non pêché, de la pente de la relation stock-recrutement de Beverton-Holt, de la mortalité naturelle, du recrutement moyen et des paramètres de sélectivité logistique pour les deux pêcheries commerciales et les quatre campagnes synoptiques. Les distributions de probabilités préalables pour le modèle de base sont présentées dans le tableau \@ref(tab:param-settings-table) et la figure \@ref(fig:fig-base-priors-posts) et décrites dans la section \@ref(scam-model-priors). La sensibilité du modèle aux paramètres fixes et aux distributions de probabilité préalables supposées est présentée à la section \@ref(sens-analyses).

Le modèle a été conditionné par les données de capture observées (`r ct_start_yr`--`r ct_end_yr`), qui ont été supposées connues sans erreur. Le modèle a été ajusté à quatre indices d'abondance de l'enquête, à l'indice de CPUE des rejets et aux données de composition par âge provenant des deux pêcheries commerciales et de trois enquêtes synoptiques. Les paramètres biologiques déterminant les calendriers de poids à l'âge et de maturité à l'âge ont été estimés indépendamment (Annexe \@ref(app:bio-data-appendix)) et introduits dans le modèle d'évaluation en tant que paramètres fixes qui sont restés constants dans le temps (Tableau \@ref(tab:growth-params-table)).

Les indices de biomasse de l'enquête ont été traités comme des indices d'abondance relative directement proportionnels à la biomasse vulnérable de l'enquête au début de chaque année. Les erreurs d'observation dans les indices d'abondance relative ont été supposées être distribuées selon une loi log-normale. Le paramètre de capturabilité $q_k$ a été estimé pour chaque indice $k$. Les distributions de probabilités préalables pour $\ln(q_k)$ sont décrites dans la section \@ref(scam-model-priors).

Les observations relatives à la composition par âge ont été supposées tirées d'une distribution Dirichlet-multinomiale. On a supposé que les âges étaient lus sans erreur.

La sélectivité en fonction de l'âge pour les pêcheries au chalut, les quatre campagnes et l'indice de CPUE des rejets a été modélisée à l'aide d'une fonction logistique à deux paramètres avec une asymptote à 1. La vulnérabilité en fonction de l'âge à 50 % ($\hat{a}_k$) et l'écart type de la courbe de sélectivité logistique ($\hat{\gamma}_k$) pour chaque engin $k$ ont été estimés pour les pêcheries au chalut et les trois campagnes synoptiques. Aucune donnée sur la composition par âge n'étant disponible pour les engins `r hsmas` et `r dcpue`, la sélectivité a été fixée avec $\hat{a}_k$ = `r f(base_model$ctl$sel[2, 4])` et $\hat{\gamma}_k$ = `r f(base_model$ctl$sel[3, 4], 1)`, de manière similaire aux valeurs estimées pour les autres engins. D'autres simulations de sensibilité non incluses dans le présent document d'évaluation ont indiqué que le modèle était peu sensible à cette hypothèse.

Les composantes de la variance du modèle ont été divisées en erreurs d'observation et erreurs de processus. Le paramètre clé est la variance totale (c'est-à-dire $\vartheta^2$, précision totale). La variance totale est divisée en composantes d'erreur d'observation et de processus par le paramètre de modèle $\rho$, qui représente la proportion de la variance totale due à l'erreur d'observation [@punt1999 ; @deriso2007]. La variance totale est divisée en erreurs d'observation ($\sigma$) et en erreurs de processus ($\tau$) à l'aide de l'équation suivante \@ref(eq:df17) de l'annexe \@ref(app:model-desc). Les paramètres $\vartheta^2$ et $\rho$ ont été fixés dans l'évaluation actuelle (tableau \@ref(tab:param-settings-table)) à des valeurs qui donnent $\sigma = 0,2$ et $\tau = 0,8$. Voir la section \@ref(sens-sigma) pour les analyses de sensibilité à cette hypothèse. Voir l'annexe \@ref(app:model-desc) pour plus de détails sur le traitement de la variance dans cette évaluation.")
```

```{r scam-priors-en, eval = !fr(), results = 'asis'}
cat("### Prior Probability Distributions {#scam-model-priors}

Prior probability distributions for the base model are shown in Figure \@ref(fig:fig-base-priors-posts) and Table \@ref(tab:param-settings-table). Model sensitivities to assumed prior distributions are presented in Sections \@ref(sens-sigma), \@ref(sens-m), and \@ref(sens-q).

Uniform prior probability distributions were assumed for $\ln(R_0)$, $\ln(\bar{R})$, $\ln(R_\mathrm{init})$ and selectivity parameters (Table \@ref(tab:param-settings-table)). A Beta distribution was assumed for the steepness ($h$) of the stock-recruit relationship, with shape parameters that resulted in a distribution with mean = `r f(base_h_prior1, 2)` and CV = `r f(base_h_prior2, 2)` (Beta($\alpha$ = `r f(base_h$p1, 1)`, $\beta$ = `r f(base_h$p2, 1)`)). This prior was based on a literature review on steepness parameters for Pacific flatfish species done by @holt2016 and was used in the `r la` for `r sp`. A review of steepness estimates for flatfish species by @maunder2012 suggested that flatfish steepness using a Beverton-Holt stock-recruit relationship may be around $0.94$ (where $h$ approaching $1.0$ implies recruitment is independent of spawning biomass).

A normal distribution was assumed for $\ln(M)$ for both sexes with mean = $\ln$(`r f(exp(base_m_female$p1), 2)`) and SD = `r f(exp(base_m_female$p2), 2)` for females and mean = $\ln$(`r f(exp(base_m_male$p1), 2)`) and SD = `r f(exp(base_m_male$p2), 2)` for males (in log space). @holt2016 reviewed the literature and stock assessments and assumed a prior probability distribution for M with mean = 0.2 in their assessment of `r bc` Rock Sole (*Lepidopsetta spp.*). @goa2021 assumed a value of M = 0.2 for females and M = 0.35 for males in the assessment of Gulf of Alaska `r sp`; the same was done for the Bering Sea Aleutian Islands stock [@bering2019].

Normal prior probability distributions were assumed for the log survey catchability parameters $\ln(q_k)$ for each survey $k$. Normal distributions with mean = $\ln$(`r base_qk_mean`) and SD = `r base_qk_sd` in log space were selected because the survey estimates of biomass were derived from swept area analysis (Eqs. \@ref(eq:swept-area), \@ref(eq:cpue-density), and \@ref(eq:survey-biomass-variance)) and could therefore reasonably be expected to be within 1–2 orders of magnitude of unity. A large standard deviation was used to reflect ignorance of the scale of the swept area analysis compared with the true biomass.")
```

```{r scam-priors-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Distributions de probabilités préalables {#scam-model-priors}

Les distributions de probabilités préalables pour le modèle de base sont présentées dans la figure \@ref(fig:fig-base-priors-posts) et le tableau \@ref(tab:param-settings-table). Les sensibilités du modèle aux distributions préalables supposées sont présentées dans les sections \@ref(sens-sigma), \@ref(sens-m) et \@ref(sens-q).

Des distributions de probabilités uniformes ont été supposées pour $\ln(R_0)$, $\ln(\bar{R})$, $\ln(R_\mathrm{init})$ et les paramètres de sélectivité (tableau \@ref(tab:param-settings-table)). Une distribution Bêta a été supposée pour la pente ($h$) de la relation stock-recrutement, avec des paramètres de forme qui ont abouti à une distribution avec une moyenne = `r f(base_h_prior1, 2)` et un CV = `r f(base_h_prior2, 2)` (Bêta($\alpha$ = `r f(base_h$p1, 1)`, $\beta$ = `r f(base_h_prior2, 1)`)). Cet a priori est basé sur une revue de la littérature sur les paramètres de pente pour les espèces de poissons plats du Pacifique réalisée par @holt2016 et a été utilisé dans le `r la` pour le `r sp`. Un examen des estimations de la pente pour les espèces de poissons plats par @maunder2012 a suggéré que la pente des poissons plats utilisant une relation stock-recrutement de Beverton-Holt pourrait être d'environ 0,94$ (où $h$ approchant 1,0$ implique que le recrutement est indépendant de la biomasse de frai).

Une distribution normale a été supposée pour $\ln(M)$ pour les deux sexes avec une moyenne = $\ln$(`r f(exp(base_m_female$p1), 2)`) et un écart-type = `r f(exp(base_m_female$p2), 2)` pour les femmes et moyenne = $\ln$(`r f(exp(base_m_male$p1), 2)`) et écart-type = `r f(exp(base_m_male$p2), 2)` pour les hommes (en espace logarithmique). @holt2016 a examiné la littérature et les évaluations des stocks et a supposé une distribution de probabilité préalable pour M avec une moyenne = 0,2 dans leur évaluation de `r bc` Rock Sole (*Lepidopsetta spp.*). @goa2021 a supposé une valeur de M = 0,2 pour les femelles et M = 0,35 pour les mâles dans l'évaluation de `r sp` du Golfe de l'Alaska ; la même chose a été faite pour le stock des îles Aléoutiennes de la mer de Béring [@bering2019].

Des distributions de probabilités normales préalables ont été supposées pour les paramètres logarithmiques de capturabilité des relevés $\ln(q_k)$ pour chaque relevé $k$. Des distributions normales avec une moyenne = $\ln$(`r base_qk_mean`) et un écart-type = `r base_qk_sd` dans l'espace logarithmique ont été sélectionnées parce que les estimations de la biomasse de l'enquête ont été dérivées de l'analyse de la zone balayée (Eqs. \@ref(eq:swept-area), \@ref(eq:cpue-density), et \@ref(eq:survey-biomass-variance)) et que l'on pouvait donc raisonnablement s'attendre à ce qu'elles se situent dans un intervalle de 1 à 2 ordres de grandeur par rapport à l'unité. Un écart-type important a été utilisé pour refléter l'ignorance de l'échelle de l'analyse de la zone balayée par rapport à la biomasse réelle.
")
```

```{r scam-fishery-reference-points-en, eval = !fr(), results = 'asis'}
cat("## FISHERY REFERENCE POINTS {#scam-ref-points}

The DFO Fishery Decision-Making Framework Incorporating the Precautionary Approach (PA) policy [@dfo2009] requires stock status to be characterized using three reference points:

1. A Reference Removal Rate
1. An Upper Stock Reference point (USR)
1. A Limit Reference Point (LRP)

Provisional values of USR = $0.8B_\mathrm{MSY}$ and LRP = $0.4B_\mathrm{MSY}$ are suggested in the absence of stock-specific reference points. The framework suggests a reference removal rate of $F_\mathrm{MSY}$. A harvest control rule based on these reference points that is coincident with the choice of LRP, USR, and removal reference would apply a linear reduction in fishing mortality as the stock falls below the USR and would cease fishing when the stock reaches the LRP [e.g., Figure 6 in @grandin2017].

The $F_\mathrm{MSY}$ (and annual harvest rate $U_\mathrm{MSY}$) are estimated to be very large in this model due to selectivity being greater than maturity, as described in Section \@ref(selex). We therefore present $B_0$-based reference points for `r sp` that are less reliant on estimated selectivity and maturity at age. We suggest an LRP = $0.2B_0$ and USR = $0.4B_0$. These are the reference points agreed to in the last assessment for `r sp` in `r bc` [@grandin2017]; we further elaborate on our reasoning below.

### Limit Reference Point (LRP)

We suggest an LRP of $0.2B_0$ as a proxy for recruitment overfishing. A value of $0.2B_0$ is a threshold below which there is typically at least some reduction in per-capita recruitment [@myers1994; @sainsbury2008]. This threshold has been recommended in recent national guidance [@barrett2022]. Furthermore, this threshold is consistent with recommendations in other jurisdictions: a limit value of $0.2B_0$ is the default recommendation (and minimum acceptable value) under Australia's Commonwealth Fisheries Harvest Strategy Policy [@dawr2018] and is the default trigger for rebuilding plans under New Zealand's Harvest Strategy [@mf2008].

### Upper Stock Reference Point (USR)

Under the PA Policy, the USR can perform two functions: (1) a 'threshold below which removals must be progressively reduced in order to avoid reaching the LRP' (an operational control point or 'OCP') and (2) a 'target reference point determined by productivity objectives for the stock, broader biological considerations, and social and economic objectives for the fishery' [@dfo2009]. @marentette2020 emphasize that the primary role of the USR is its first role, as an OCP, to avoid the LRP. The PA Policy describes how the USR is meant to be developed by fishery managers with consultation with interested parties and advice from Science. We therefore provide the following science advice regarding the USR. 

First, one rationale for choosing $0.4B_0$ is that under a Schaefer surplus production model, $B_\mathrm{MSY}$ is 0.5 $B_0$ and since 0.8 $B_\mathrm{MSY}$ is the provisional USR and 0.8 $\times$ 0.5 = 0.4, $0.4B_0$ is the equivalent $B_0$-based USR. A similar rationale applies to $0.2B_0$ as the LRP: 0.4 $B_\mathrm{MSY}$ is the provisional LRP and 0.4 $\times$ 0.5 = 0.2 resulting in 0.2 $B_0$ as the LRP.
  
In addition, there is a rationale regarding the USR's role in triggering fishery reductions to reduce risk of the stock breaching the LRP. The PA Policy notes that 'while socio-economic factors may influence the location of the USR, these factors must not diminish its minimum function in guiding management of the risk of approaching the LRP'. We suggest the following scientific factors should be considered with respect to the timing of adjusting fishing intensity as the stock approaches the LRP: (1) the level of uncertainty around the relative spawning biomass; (2) the frequency of assessment; (3) the availability of important data sources; and (4) plausible future rates of decline. We present the following advice with respect to these factors for Arrowtooth Flounder (as will be shown in the results):

1. The level of uncertainty around relative biomass is reasonably high with the 95% CIs roughly spanning the width between $0.2B_0$ and $0.4B_0$. Greater uncertainty means the USR would need to be spaced further from the LRP to ensure an equivalent risk tolerance.
  
2. Although it has been several years since the last assessment, we recommend the stock assessment be updated approximately every two years, when an additional year of data is available from each survey. Longer gaps between assessments would require the USR to be further spaced from the LRP to ensure an equivalent risk.

3. Commercial age samples have not been available for this stock since 2019 and it unclear when this sampling will resume. These data provide a critical source of information about recruitment and selectivity. The assessment results show that declines in estimated recruitment over the last decade are responsible for a large part of the recent estimated declines in SSB. The lack of age samples may introduce uncertainty going forward, which would suggest a larger gap between the LRP and USR for an equivalent risk compared to having this information.
  
4. Although the stock is estimated to have undergone a relatively rapid decline in SSB from about 2012 to 2020, this was associated with higher F's than are currently estimated and this past trajectory is not necessarily indicative of future possible trajectories. A closed-loop simulation analysis would be a rigorous way of evaluating plausible stock trajectories and the ability for a given USR to provide sufficient time to avoid the stock biomass falling below the LRP. We therefore have little information currently about plausible future rates of decline.

Several other juridisctions worldwide suggest or legislate targets near 0.4$B_0$ when status is assessed relative to $B_0$; however, these jurisdictions also use this 'target' as an operational control point (OCP) below which fishing mortality $F$ is to be reduced to avoid hitting a lower limit reference point [@punt2008, and references therein]. It is our understanding that the North Pacific Fishery Management Council (NPFMC) in Alaska would use an upper OCR of 0.4$B_0$ for this Arrowtooth Flounder stock with $F$ ramped down when biomass is below this level ['Tier 3 3b', p. 19 in @npfmc2020]. The US West Coast Pacific Fishery Management Council (PFMC) also uses 0.4$B_0$ as a standard groundfish OCP to ramp down $F$ [@pfmc2022], although a flatfish-specific OCP of 0.25 $B_0$ was added in 2010 [Amendment 16-5 @nmfs2010]. However, this is under the assumption that flatfish stocks are often more productive than other groundfish stocks, which may not bear out for this BC stock with low estimated recruitment over the last decade. Australia uses maximum economic yield (MEY) as their legislated objective, which they suggest can be approximated as $0.4 B_0 \times 1.2 = 0.48 B_0$; this then acts as an OCP with exploitation rate ramped down below 0.48 $B_0$ [p. 9 and 22 in @dawr2018]. In other words, in these jurisidictions, their 'target' matches the primary definition of the Canadian USR [@marentette2020] as an OCP. This interpretation would suggest that, despite the use of the term 'target' elsewhere, a USR  would be equivalent in function to these jurisdictions. Most equivalent in function to these jurisdictions would be to consider 0.4$B_0$ both a 'target' and a USR OCP rather than how they are separated in the PA Policy diagram.                                   

Finally, from a science perspective, we note that 0.4$B_0$ was previously accepted as the USR for Arrowtooth Flounder [@grandin2017]. We caution that reducing reference points when there is evidence of declining recruitment and declining stock trends would be inconsistent with the precautionary approach as outlined in the DFO PA Policy. Such 'moving the reference point goalposts' can have considerable implications for fisheries sustainability [@silvar-viladomiu2021].

### Reference removal rate {#reference-removal-rate}

Although the PA Policy recommends $F_\mathrm{MSY}$ as a provisional reference removal, for reasons outlined above, we suggest $B_0$-based reference points for this stock. We suggest that an equivalent reference removal rate would be the fishing mortality $F$ that would take the stock to $0.4 B_0$ at equilibrium given recently observed recruitment. We determined this by projecting the stock 50 years into the future with recruitment deviations randomly drawn with replacement from 2010--2019 (omitting the poorly estimated 2020 and 2021 deviations), using an optimization routine to find the constant catch that would generate SSB matching $0.4 B_0$ within a tolerance of 50 t. We report the associated $F$ at the end of 50 years. Given sufficient projection years, performing the projections with a constant $F$ or a constant catch should render the same conclusion.
")
```

```{r scam-fishery-reference-points-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## POINTS DE RÉFÉRENCE DE LA PÊCHE {#scam-ref-points}

Le cadre décisionnel pour la pêche du MPO intégrant la politique de l'approche de précaution (AP) [@dfo2009] exige que l'état des stocks soit caractérisé à l'aide de trois points de référence :

1. Un taux de prélèvement de référence
1. Un point de référence du stock supérieur (RSS)
1. Un point de référence limite (PRL)

Des valeurs provisoires de RSS = $0.8B_\mathrm{RMD}$ et PRL = $0.4B_\mathrm{RMD}$ sont suggérées en l'absence de points de référence spécifiques aux stocks. Le cadre suggère un taux de prélèvement de référence de $F_\mathrm{RMD}$. Une règle de contrôle de l'exploitation basée sur ces points de référence qui coïncide avec le choix du PLR, du RSS et de la référence de prélèvement appliquerait une réduction linéaire de la mortalité par pêche lorsque le stock tombe en dessous du RSS et cesserait de pêcher lorsque le stock atteint le PLR [par exemple, figure 6 dans @grandin2017].

Le $F_\mathrm{RMD}$ (et le taux de capture annuel $U_\mathrm{RMD}$) est estimé être très important dans ce modèle en raison de la sélectivité qui est supérieure à la maturité, comme décrit dans la section \@ref(selex). Nous présentons donc des points de référence basés sur $B_0$ pour `r sp` qui sont moins dépendants de la sélectivité estimée et de la maturité à l'âge. Nous suggérons un PRL = $0,2B_0$ et un RSS = $0,4B_0$. Il s'agit des points de référence convenus lors de la dernière évaluation pour `r sp` dans `r bc` [@grandin2017]; nous expliquons plus en détail notre raisonnement ci-dessous.

### Point de Référence Limite (PRL)

Nous suggérons un PRL de 0,2B_0$ comme indicateur de la surpêche de recrutement. Une valeur de 0,2B_0$ est un seuil en dessous duquel il y a généralement au moins une certaine réduction du recrutement par habitant [@myers1994 ; @sainsbury2008]. Ce seuil a été recommandé dans les récentes orientations nationales [@barrett2022]. En outre, ce seuil est conforme aux recommandations d'autres juridictions : une valeur limite de 0,2B_0$ est la recommandation par défaut (et la valeur minimale acceptable) dans le cadre de la politique de stratégie de récolte des pêcheries du Commonwealth australien [@dawr2018] et constitue le déclencheur par défaut des plans de reconstitution dans le cadre de la stratégie de récolte de la Nouvelle-Zélande [@mf2008].

### Point de Référence Supérieur du Stock (RSS)

Dans le cadre de la politique de l'AP, l'RSS peut remplir deux fonctions: (1) un 'seuil en dessous duquel les prélèvements doivent être progressivement réduits afin d'éviter d'atteindre le PLR' (un point de contrôle opérationnel ou 'PCO') et (2) un 'point de référence cible déterminé par des objectifs de productivité pour le stock, des considérations biologiques plus larges, et des objectifs sociaux et économiques pour la pêcherie' [@dfo2009]. @marentette2020 souligne que le rôle principal de l'RSS est son premier rôle, en tant qu'PCO, pour éviter le PRL. La politique de l'AP` décrit comment l'RSS est censée être développée par les gestionnaires de la pêche en consultation avec les parties intéressées et avec l'avis des scientifiques. Nous fournissons donc l'avis scientifique suivant concernant l'RSS. 

Premièrement, l'une des raisons du choix de $0,4B_0$ est que, dans le cadre d'un modèle de production excédentaire de Schaefer, $B_\mathrm{RMD}$ est égal à $0,5B_0$ et, étant donné que $0,8B_\mathrm{RMD}$ est le RSS provisoire et que 0,8 $\mathrm{RMD}$ fois 0.8 $\times$ 0.5 = 0.4, $0.4B_0$ est le RSS équivalent basé sur le $B_0$. Un raisonnement similaire s'applique à $0,2B_0$ en tant que PRL: 0,4 $B_\mathrm{RMD}$ est le PLR provisoire et $0,4 \times 0,5 = 0,2$, ce qui donne $0,2B_0$ en tant que PLR.
  
En outre, il existe une justification concernant le rôle de l'RSS dans le déclenchement des réductions de la pêche afin de réduire le risque de dépassement du PRL par le stock. La politique de l'AP note que 'si des facteurs socio-économiques peuvent influencer l'emplacement de l'RSS, ces facteurs ne doivent pas diminuer sa fonction minimale d'orientation de la gestion du risque de dépassement du PRL'. Nous suggérons que les facteurs scientifiques suivants soient pris en compte en ce qui concerne le moment de l'ajustement de l'intensité de la pêche lorsque le stock s'approche du PRL: (1) le niveau d'incertitude autour de la biomasse reproductrice relative; (2) la fréquence de l'évaluation; (3) la disponibilité de sources de données importantes; et (4) les futurs taux de déclin plausibles. Nous présentons les conseils suivants en ce qui concerne ces facteurs pour la plie rouge (comme le montreront les résultats) :

1. Le niveau d'incertitude concernant la biomasse relative est raisonnablement élevé, les IC à 95 % couvrant approximativement la largeur entre $0,2B_0$ et $0,4B_0$. Une plus grande incertitude signifie que l'RSS devrait être plus éloignée du PRL pour garantir une tolérance au risque équivalente.
  
2. Bien que plusieurs années se soient écoulées depuis la dernière évaluation, nous recommandons que l'évaluation du stock soit mise à jour tous les deux ans environ, lorsqu'une année supplémentaire de données est disponible pour chaque étude. Des intervalles plus longs entre les évaluations nécessiteraient que l'RSS soit plus éloignée du PRL afin de garantir un risque équivalent.

3. Les échantillons d'âge commerciaux ne sont pas disponibles pour ce stock depuis 2019 et la date de reprise de cet échantillonnage n'est pas claire. Ces données constituent une source essentielle d'informations sur le recrutement et la sélectivité. Les résultats de l'évaluation montrent que les baisses du recrutement estimé au cours de la dernière décennie sont responsables d'une grande partie des récentes baisses estimées de la SSB. L'absence d'échantillons d'âge peut introduire une incertitude pour l'avenir, ce qui suggérerait un écart plus important entre le PRL et le RSS pour un risque équivalent par rapport à l'existence de ces informations.

4. Bien que l'on estime que le stock a connu une baisse relativement rapide de la SSB entre 2012 et 2020 environ, cette baisse a été associée à des F plus élevés que ceux estimés actuellement et cette trajectoire passée n'est pas nécessairement indicative des trajectoires futures possibles. Une analyse de simulation en boucle fermée constituerait un moyen rigoureux d'évaluer les trajectoires plausibles du stock et la capacité d'une RSS donnée à fournir suffisamment de temps pour éviter que la biomasse du stock ne tombe en dessous du PRL. Nous disposons donc actuellement de peu d'informations sur les taux de déclin futurs plausibles.

Plusieurs autres juridictions dans le monde suggèrent ou légifèrent des cibles proches de $0,4B_0$ lorsque l'état est évalué par rapport à $B_0$ ; cependant, ces juridictions utilisent également cette 'cible' comme point de contrôle opérationnel (PCO) en dessous duquel la mortalité par pêche $F$ doit être réduite pour éviter d'atteindre un point de référence de limite inférieure [@punt2008, et les références qui y sont citées]. Nous croyons comprendre que le Conseil de gestion des pêches du Pacifique Nord (CGPPN) en Alaska utiliserait un PCO supérieur de $0,4B_0$ pour ce stock de flétan noir, avec une réduction progressive de $F$ lorsque la biomasse est inférieure à ce niveau ['Tier 3 3b', p. 19 dans @npfmc2020]. Le Conseil de gestion des pêches du Pacifique de la côte ouest des États-Unis (PFMC) utilise également $0,4B_0$ comme OCP standard pour les poissons de fond afin de réduire progressivement $F$ [@pfmc2022], bien qu'un PCO spécifique aux poissons plats de $0,25B_0$ ait été ajouté en 2010 [Amendement 16-5 @nmfs2010]. Toutefois, cela repose sur l'hypothèse que les stocks de poissons plats sont souvent plus productifs que les autres stocks de poissons de fond, ce qui pourrait ne pas être le cas pour ce stock de C.-B. dont le recrutement a été estimé faible au cours de la dernière décennie. L'Australie utilise le Rendement économique maximal (REM) comme objectif législatif, qu'elle suggère d'approximer comme $0.4B_0 \times 1.2 = 0.48B_0$; ceci agit alors comme un PCO avec un taux d'exploitation ramené en dessous de $0,48B_0$ [p. 9 et 22 dans @dawr2018]. En d'autres termes, dans ces juridictions, leur 'cible' correspond à la définition primaire de l'RSS canadienne [@marentette2020] en tant qu'PCO. Cette interprétation suggère que, malgré l'utilisation du terme 'cible' ailleurs, une RSS serait équivalente en termes de fonction dans ces juridictions. La fonction la plus équivalente à ces juridictions serait de considérer $0,4B_0$ à la fois comme une 'cible' et comme une PCO RSS, plutôt que de la manière dont elles sont séparées dans le diagramme de la politique de l'AP.

Enfin, d'un point de vue scientifique, nous notons que $0,4B_0$ a été précédemment accepté comme RSS pour la plie rouge [@grandin2017]. Nous avertissons que la réduction des points de référence lorsqu'il existe des preuves de la baisse du recrutement et des tendances du stock serait incompatible avec l'approche de précaution telle que décrite dans la politique d'AP du MPO. Un tel 'déplacement des poteaux de référence' peut avoir des implications considérables pour la durabilité des pêcheries [@silvar-viladomiu2021].

### Taux de prélèvement de référence {#reference-removal-rate}

Bien que la politique de l'AP recommande $F_\mathrm{RMD}$ comme taux de prélèvement de référence provisoire, pour les raisons exposées ci-dessus, nous suggérons des points de référence basés sur $B_0$ pour ce stock. Nous suggérons qu'un taux de prélèvement de référence équivalent serait la mortalité par pêche $F$ qui amènerait le stock à $0,4B_0$ à l'équilibre, compte tenu du recrutement récemment observé. Nous avons déterminé cela en projetant le stock 50 ans dans le futur avec des déviations de recrutement tirées au hasard avec remplacement de 2010 à 2019 (en omettant les déviations mal estimées de 2020 et 2021), en utilisant une routine d'optimisation pour trouver la prise constante qui générerait une SSB correspondant à $0,4B_0$ dans une tolérance de 50 t. Nous rapportons le $F$ associé à la fin des 50 ans. Compte tenu d'un nombre suffisant d'années de projection, l'exécution des projections avec un $F$ constant ou une prise constante devrait aboutir à la même conclusion.

")
```

```{r dynamic-bo-en, eval = !fr(), results = 'asis'}
cat("### Dynamic $B_0$ {#dynamic-bo}

A dynamic $B_0$ was calculated by recreating the population dynamics model in R with parameter estimates from the fitted base model. The fishing mortality was set to zero but estimated recruitment deviations were included. Figure \@ref(fig:fig-dynamic-b-zero) shows the estimated dynamic $B_0$ from this exercise.
This figure illustrates that the model explains a portion of the recent decline by a sequence of poor recruitment.
")
```

```{r dynamic-bo-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### DYNAMIQUE $B_0$ {#dynamic-bo}

Un $B_0$ dynamique a été calculé en recréant le modèle de dynamique des populations dans R avec les estimations des paramètres du modèle de base ajusté. La mortalité par pêche a été fixée à zéro, mais les écarts de recrutement estimés ont été inclus. La figure \@ref(fig:fig-dynamic-b-zero) montre la dynamique estimée $B_0$ à partir de cet exercice.
Cette figure montre que le modèle explique une partie du déclin récent par une séquence de faible recrutement.")
```
