```{r bridging-para-01-en, eval = !fr(), results = 'asis'}
cat("## RESULTS
### Bridge Models {#bridging}
A set of bridging models was run to determine the effects of incremental model modifications while moving from the single-sex, single-fleet `r la` model to the split-sex, two-fleet model used in this assessment.

The base model from the `r la` [@grandin2017] was run with the newest version of the `r iscam` [@iscam] code and the original data files. The parameter estimates, reference points, estimated trajectories, index fits, and age composition fits were determined to be identical. The 2015 model was a female-only catch-at-age model with 4 indices of abundance, which included the three Synoptic surveys and the Hecate Strait Multispecies assemblage survey.

The Technical Working Group (TWG) agreed that the model should be split-sex, based on the sexual dimorphism observed in the age and length data for this species, and there being 8 more years of data since the `r la`, which allowed for a larger number of age proportion specimens for each sex.

All bridge models were run using MCMC (Markov chain Monte Carlo) sampling with a chain length of `r f(mcmc_chain_length)`, retaining every `r f(mcmc_sample_freq)`th sample, giving `r f(mcmc_num_samples)` samples, which were then burned in by `r f(mcmc_burn_in)` giving a total of `r f(mcmc_actual_samples)` samples used for inference.
")
```
```{r bridging-para-01-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## RÉSULTATS
### Modèles de transition {#bridging}
Un ensemble de modèles de transition a été exécuté pour déterminer les effets des modifications incrémentielles du modèle lors du passage du modèle `r la` unisexe et à flotte unique au modèle unisexe et à flotte double utilisé dans cette évaluation.

Le modèle de base du `r la` [@grandin2017] a été exécuté avec la dernière version du code `r iscam` [@iscam] et les fichiers de données originaux. Les estimations des paramètres, les points de référence, les trajectoires estimées, les ajustements de l'indice et les ajustements de la composition par âge ont été jugés identiques. Le modèle de 2015 était un modèle de capture à l'âge pour les femelles uniquement, avec 4 indices d'abondance, qui incluaient les trois relevés synoptiques et le relevé d'assemblage multispécifique du détroit d'Hécate.

Le Groupe de travail technique (GTT) a convenu que le modèle devait être divisé en deux sexes, sur la base du dimorphisme sexuel observé dans les données d'âge et de longueur pour cette espèce, et du fait qu'il y avait 8 années supplémentaires de données depuis le `r la`, ce qui permettait d'avoir un plus grand nombre de spécimens proportionnels à l'âge pour chaque sexe.

Tous les modèles de pont ont été exécutés en utilisant un échantillonnage MCMC (Markov chain Monte Carlo) avec une longueur de chaîne de `r f(mcmc_chain_length)`, retenant chaque `r f(mcmc_sample_freq)`ème échantillon, ce qui donne `r f(mcmc_num_samples)` échantillons, qui ont ensuite été brûlés par `r f(mcmc_burn_in)` donnant un total de `r f(mcmc_actual_samples)` échantillons utilisés pour l'inférence.
")
```

\clearpage

```{r bridging-para-02-en, eval = !fr(), results = 'asis'}
cat("Each model in this list is based on the previous one with only one change made so incremental changes can be tracked.

1. 2015 Base model [@grandin2017].
1. Extracted the data for the 2015 model using the [gfdata](https://github.com/pbs-assess/gfdata)/[gfplot](https://github.com/pbs-assess/gfplot) packages, which have been used in several assessments and in the [gfsynopsis](https://github.com/pbs-assess/gfsynopsis) report [@anderson2019synopsis; @dfo2022synopsis].
1. Using the same data extraction methods as in the previous step, appended data up to and including 2021. The proportion female was changed in this step from 0.70 to `r total_prop_female`.
1. Added the `r wchgs` index and age composition data. This was tried to determine how the additional survey years since 2015 contributed to the model fit.
1. Switched the age composition likelihood from multinomial to the saturating parameterization of the Dirichlet-multinomial [@thorson2016]. We did this because in more complex model configurations, the multivariate normal logistic had convergence issues and the standard multinomial would have required manually re-weighting the age proportions for each model run [@francis2016].
1. Changed the model from one to two commercial fleets. This splits the commercial trawl catch into catch from Freezer Trawlers and Shoreside fleets. This was done on the recommendation of the Technical Working Group (TWG) since the large freezer trawlers may fish differently and have different selectivity than the shoreside vessels.
1. Added a Discard CPUE index. This was suggested by the TWG and is an index of catch per unit effort for vessels that were not fishing for `r sp` and therefore were discarding all that they caught incidentally. The selectivity could not be estimated for this index since there are no age composition data for it, so its selectivity was fixed to values representative of other estimated selectivities from other gears. See Appendix \@ref(app:dcpue) for details on how this index was generated.
1. Converted the model from female-only to a split-sex model. In this model, the two natural mortality parameters for male and female were estimated.
1. Changed fishing year to start on February 21 (vs. January 1), which is the date currently used by Fisheries Management for the fishing year.
1. Removed the `r wchgs` index and age comps. The survey was not contributing meaningfully to the assessment and the estimated selectivities were not viable due to too few samples. Its removal was suggested by the TWG.
1. Fixed both male and female natural mortality parameters. The estimated values were quite low for this species based on assessments in neighbouring jurisdictions [@goa2017; @goa2019; @goa2020; @goa2021].

")
```

```{r bridging-para-02-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("Chaque modèle de cette liste est basé sur le précédent avec une seule modification afin de pouvoir suivre les changements incrémentaux.

1. Modèle de base 2015 [@grandin2017].
1. Extraction des données pour le modèle 2015 à l'aide des packages [gfdata](https://github.com/pbs-assess/gfdata)/[gfplot](https://github.com/pbs-assess/gfplot), qui ont été utilisés dans plusieurs évaluations et dans le rapport [gfsynopsis](https://github.com/pbs-assess/gfsynopsis) [@anderson2019synopsis; @dfo2022synopsis].
1. En utilisant les mêmes méthodes d'extraction de données qu'à l'étape précédente, les données ont été ajoutées jusqu'en 2021 inclus. La proportion de femmes a été modifiée dans cette étape, passant de 0,70 à `r total_prop_female`.
1. Ajout de l'indice `r wchgs` et des données sur la composition par âge. On a essayé de déterminer comment les années d'enquête supplémentaires depuis 2015 contribuaient à l'ajustement du modèle.
1. Nous avons changé la vraisemblance de la composition par âge de multinomiale à la paramétrisation saturante de la Dirichlet-multinomiale [@thorson2016]. Nous avons fait cela parce que dans les configurations de modèles plus complexes, la logistique normale multivariée avait des problèmes de convergence et le multinomial standard aurait nécessité de repondérer manuellement les proportions d'âge pour chaque exécution du modèle [@francis2016].
1. Le modèle est passé d'une à deux flottes commerciales. Cela divise la prise commerciale au chalut en prise des chalutiers congélateurs et des flottes côtières. Ceci a été fait sur la recommandation du groupe de travail technique (TWG) puisque les grands chalutiers congélateurs peuvent pêcher différemment et avoir une sélectivité différente de celle des navires côtiers.
1. Ajout d'un indice de CPUE des rejets. Il s'agit d'un indice de capture par unité d'effort pour les navires qui ne pêchaient pas de `r sp` et qui rejetaient donc tout ce qu'ils capturaient accidentellement. La sélectivité n'a pas pu être estimée pour cet indice car il n'existe pas de données sur la composition par âge, de sorte que sa sélectivité a été fixée à des valeurs représentatives d'autres sélectivités estimées pour d'autres engins. Voir l'annexe \@ref(app:dcpue) pour plus de détails sur la façon dont cet indice a été généré.
1. Conversion du modèle de la femelle uniquement en un modèle à deux sexes. Dans ce modèle, les deux paramètres de mortalité naturelle pour les mâles et les femelles ont été estimés.
1. Modification de l'année de pêche pour qu'elle commence le 21 février (au lieu du 1er janvier), qui est la date actuellement utilisée par la gestion des pêches pour l'année de pêche.
1. Suppression de l'indice `r wchgs` et des comps d'âge. L'enquête ne contribuait pas de manière significative à l'évaluation et les sélectivités estimées n'étaient pas viables en raison du nombre insuffisant d'échantillons. Sa suppression a été suggérée par le GTT.
1. Fixation des paramètres de mortalité naturelle des mâles et des femelles. Les valeurs estimées étaient assez faibles pour cette espèce d'après les évaluations réalisées dans les juridictions voisines [@goa2017; @goa2019; @goa2020; @goa2021].

")
```

```{r bridging-para-03-en, eval = !fr(), results = 'asis'}
cat("
**Bridge models group 1 (models 1-4)**
Figure \@ref(fig:bridge-biomass-group1) shows the absolute and relative spawning biomass for the first four bridging models in the list above (list items 1--4). Changing the data extraction method for all data up to 2014 had minimal effect, with only a small difference in 2015 absolute biomass and a very small difference in 2015 relative biomass. Small changes in data are mainly due to changes in survey indices, which are caused by survey blocks being removed from the entire survey series. These blocks were found to be unfishable or inappropriate for the index in the surveys since 2014 and were removed from the entire series, changing the historical indices slightly from those included in the `r la`.

Adding the data from 2015--`r base_model$dat$end.yr` caused a large change in the biomass trajectories (Figure \@ref(fig:bridge-biomass-group1)). The biomass began dropping more rapidly starting in 2002, with a relatively steep drop from 2010--2020. This decline in the biomass is caused mainly by the declining indices of abundance in that time period. From 2021--2022 the model shows the beginnings of an upward trend. Credible intervals (CIs) became much narrower with the addition of the 2015--`r base_model$dat$end.yr` data. However, the estimated parameters (except steepness) are all moderately to highly correlated (Figure \@ref(fig:fig-bridge3-pairs)). All the bridging models that follow have high correlation between parameters, except for the last one in which the natural mortalities for both sexes were fixed.

Adding the `r wchgs` age compositions and index into the model had a scaling effect in the earlier part of the trajectory, but both absolute and relative biomasses were nearly identical for 2022 (Figure \@ref(fig:bridge-biomass-group1)).

")
```

```{r bridging-para-03-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("
**Modèles de pont groupe 1 (modèles 1-4)**
La figure \@ref(fig:bridge-biomass-group1) montre la biomasse de frai absolue et relative pour les quatre premiers modèles de transition de la liste ci-dessus (éléments de la liste 1--4). Le changement de la méthode d'extraction des données pour toutes les données jusqu'en 2014 n'a eu qu'un effet minime, avec seulement une petite différence dans la biomasse absolue de 2015 et une très petite différence dans la biomasse relative de 2015. Les petits changements dans les données sont principalement dus à des changements dans les indices d'enquête, qui sont causés par des blocs d'enquête qui ont été retirés de la série d'enquête entière. Ces blocs ont été jugés non pêchables ou inappropriés pour l'indice dans les enquêtes depuis 2014 et ont été retirés de l'ensemble de la série, modifiant légèrement les indices historiques par rapport à ceux inclus dans le `r la`.

L'ajout des données de 2015 - `r base_model$dat$end.yr` a provoqué un changement important dans les trajectoires de la biomasse (Figure \@ref(fig:bridge-biomass-group1)). La biomasse a commencé à chuter plus rapidement à partir de 2002, avec une chute relativement importante entre 2010 et 2020. Cette baisse de la biomasse est principalement due à la diminution des indices d'abondance au cours de cette période. À partir de 2021-2022, le modèle montre le début d'une tendance à la hausse. Les intervalles de crédibilité (IC) sont devenus beaucoup plus étroits avec l'ajout des données 2015--`r base_model$dat$end.yr`. Cependant, les paramètres estimés (à l'exception de la pente) sont tous modérément à fortement corrélés (Figure \@ref(fig:fig-bridge3-pairs)). Tous les modèles de transition qui suivent ont une corrélation élevée entre les paramètres, à l'exception du dernier dans lequel les mortalités naturelles pour les deux sexes ont été fixées.

L'ajout de la composition par âge et de l'indice `r wchgs` dans le modèle a eu un effet d'échelle dans la première partie de la trajectoire, mais les biomasses absolues et relatives étaient presque identiques pour 2022 (Figure \@ref(fig:bridge-biomass-group1)).
")
```

```{r bridging-para-04-en, eval = !fr(), results = 'asis'}
cat("**Bridge models group 2 (models 5-8)**
Figure \@ref(fig:bridge-biomass-group2) shows the absolute and relative spawning biomass for the second group of four bridging models (list items 5--8). Changing the age data weighting to the saturated Dirichlet multinomial (DM) [@thorson2016], caused a drop in absolute biomass and $B_0$. The $B_0$ median for the first model in Figure \@ref(fig:bridge-biomass-group2), when compared to the $B_0$ median for the last model in Figure \@ref(fig:bridge-biomass-group1) shows a difference of  `r f(as.numeric(bvals[[1]][[4]]$bo[1]) - as.numeric(bvals[[2]][[1]]$bo[1]))` thousand t (from `r bvals[[1]][[4]]$bo[1]` to `r bvals[[2]][[1]]$bo[1]` thousand t). However, the biomass estimates were also scaled down, so the `r bvals[[1]][[4]]$depl[3]` relative biomass only dropped a small amount (from `r bvals[[1]][[4]]$depl[1]` to `r bvals[[2]][[1]]$depl[1]`).
    
For the next bridging model, the commercial trawl fishery was split into two fleets: the `r base_model$dat$fleet_gear_names[1]` and `r base_model$dat$fleet_gear_names[2]` fleets. This changed the model internals but had negligible effect on the biomass and relative biomass trajectories (Figure \@ref(fig:bridge-biomass-group2)).

Adding the `r dcpue` (DCPUE) to the model had almost no effect on the absolute biomass and $B_0$ estimates. It did, however, reduce the credible interval (Figure \@ref(fig:bridge-biomass-group2)) on the absolute spawning biomass time series.

The next step in the bridging was to convert the model into a split-sex model. All previous bridge models were female-only. This step involved significant modifications to the `r iscam` model code. This change caused a drop in final-year biomass and relative biomass, and some overall scaling up of the historical relative biomass trajectory (Figure \@ref(fig:bridge-biomass-group2)). The selectivity age-at-50% estimates ($\hat{a}$) for females in the `r wchgs` for this model were unreasonable at `r split_sex_model_sel_ahat` years.
")
```

```{r bridging-para-04-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("**Groupe de modèles de transition 2 (modèles 5-8)**
La figure \@ref(fig:bridge-biomass-group2) montre la biomasse de frai absolue et relative pour le deuxième groupe de quatre modèles de pontage (éléments de liste 5--8). La modification de la pondération des données sur l'âge en faveur de la méthode multinomiale de Dirichlet saturée (DM) [@thorson2016] a entraîné une baisse de la biomasse absolue et de $B_0$. La médiane $B_0$ pour le premier modèle de la figure \@ref(fig:bridge-biomass-group2), comparée à la médiane $B_0$ pour le dernier modèle de la figure \@ref(fig:bridge-biomass-group1), montre une différence de `r f(as.numeric(bvals[[1]][[4]]$bo[1]) - as.numeric(bvals[[2]][[1]]$bo[1]))` mille t (de `r bvals[[1]][[4]]$bo[1]` à `r bvals[[2]][[1]]$bo[1]` mille t). Toutefois, les estimations de la biomasse ont également été réduites, de sorte que la biomasse relative de `r bvals[[1]][[4]]$depl[3]` n'a diminué que légèrement (de `r bvals[[1]][[4]]$depl[1]` à `r bvals[[2]][[1]]$depl[1]`).
    
Pour le modèle de transition suivant, la pêche commerciale au chalut a été divisée en deux flottes : les flottes `r base_model$dat$fleet_gear_names[1]` et `r base_model$dat$fleet_gear_names[2]`. Cela a modifié les éléments internes du modèle mais a eu un effet négligeable sur les trajectoires de la biomasse et de la biomasse relative (figure \@ref(fig:bridge-biomass-group2)).

L'ajout de `r dcpue` (DCPUE) au modèle n'a eu pratiquement aucun effet sur les estimations de la biomasse absolue et de $B_0$. Elle a cependant réduit l'intervalle de crédibilité (Figure \@ref(fig:bridge-biomass-group2)) sur la série temporelle de la biomasse de frai absolue.

L'étape suivante du rapprochement a consisté à convertir le modèle en un modèle à deux sexes. Tous les modèles de pont précédents étaient exclusivement féminins. Cette étape a impliqué des modifications significatives du code du modèle `r iscam`. Ce changement a entraîné une baisse de la biomasse de l'année finale et de la biomasse relative, ainsi qu'une augmentation globale de la trajectoire historique de la biomasse relative (figure \@ref(fig:bridge-biomass-group2)). Les estimations de la sélectivité de l'âge à 50% ($\hat{a}$) pour les femelles dans les `r wchgs` pour ce modèle étaient déraisonnables à `r split_sex_model_sel_ahat` ans.

")
```

```{r bridging-para-05-en, eval = !fr(), results = 'asis'}
cat("**Bridge models group 3 (models 9--13)**
The biomass plots for the final group of bridging models (list items 9-13) can be found in Figure \@ref(fig:bridge-biomass-group3). For the first of these models, the fishing year was changed from what it was in the `r la`, January 1--December 31 to February 21--February 20. This change was made to reflect the start date for the fishery each year in Canada (February 21). The effect of this is the median $B_0$ increasing a small amount from `r bvals[[2]][[4]]$sbo[1]` to `r bvals[[3]][[1]]$sbo[1]` thousand t, and the `r bvals[[2]][[4]]$depl[3]` relative biomass being reduced from `r bvals[[2]][[4]]$depl[1]` to `r bvals[[3]][[1]]$depl[1]`. The credible interval of the absolute biomass is reduced by a large amount with this change in fishery timing from `r bvals[[2]][[4]]$sbt[2]` to `r bvals[[3]][[1]]$sbt[2]`. The credible interval on the relative biomass is also much smaller than the previous model in group 2; `r bvals[[2]][[4]]$depl[2]` for the previous model vs. `r bvals[[3]][[1]]$depl[2]` for the one with the fishery timing change (Figure \@ref(fig:bridge-biomass-group3)). This tiny credibility interval indicates that the parameters are highly auto-correlated, which can be seen in Figures \@ref(fig:fig-bridge-fishing-year-autocor) and \@ref(fig:fig-bridge-fishing-year-selpars-autocor).
    
The `r wchgs` was removed (it was also removed in the `r la`) as it had little effect on the biomass and poor selectivity estimates (Figure \@ref(fig:bridge-biomass-group3)). The result was a scaled-down biomass trajectory, with a similar relative biomass to the previous model.

The natural mortality estimates from the model at this point were `r bvals[[3]][[2]]$m_male[1]` for males and `r bvals[[3]][[2]]$m_female[1]` for females with credible intervals of `r bvals[[3]][[2]]$m_male[2]` and `r bvals[[3]][[2]]$m_female[2]` respectively. The female estimate of natural mortality was close to the fixed value for females in assessments done in neighbouring jurisdictions (0.20), but the male estimate was much lower than what was used in neighboring stocks (0.35). Based on the estimated natural mortality values and the high correlation between estimated parameters for this model (Figure \@ref(fig:fig-bridge10-pairs)), we decided to fix the natural mortalities at the same values as the Gulf of Alaska and Bering Sea and Aleutian Islands assessments [@goa2021; @goa2020; @goa2019; @bering2019]; 0.20 for females and 0.35 for males.
")
```

```{r bridging-para-05-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("**Groupe de modèles de transition 3 (modèles 9--13)**
Les diagrammes de biomasse pour le dernier groupe de modèles de transition (éléments de la liste 9-13) figurent dans la figure \@ref(fig:bridge-biomass-group3). Pour le premier de ces modèles, l'année de pêche a été modifiée par rapport à ce qu'elle était dans le `r la`, à savoir du 1er janvier au 31 décembre, au 21 février au 20 février. Ce changement a été effectué pour refléter la date de début de la pêche chaque année au Canada (21 février). Cela a pour effet d'augmenter légèrement la médiane $B_0$ de `r bvals[[2]][[4]]$sbo[1]` à `r bvals[[3]][[1]]$sbo[1]` mille t, et la `r bvals[[2]][[4]]$depl[3]` biomasse relative étant ramenée de `r bvals[[2]][[4]]$depl[1]` à `r bvals[[3]][[1]]$depl[1]`. L'intervalle de crédibilité de la biomasse absolue est fortement réduit par cette modification de la période de pêche, qui passe de `r bvals[[2]][[4]]$sbt[2]` à `r bvals[[3]][[1]]$sbt[2]`. L'intervalle de crédibilité de la biomasse relative est également beaucoup plus petit que celui du modèle précédent dans le groupe 2 ; `r bvals[[2]][[4]]$depl[2]` pour le modèle précédent contre `r bvals[[3]][[1]]$depl[2]` pour le modèle avec changement de période de pêche (figure \@ref(fig:bridge-biomass-group3)). Ce minuscule intervalle de crédibilité indique que les paramètres sont fortement autocorrélés, comme le montrent les figures \@ref(fig:fig-bridge-fishing-year-autocor) et \@ref(fig:fig-bridge-fishing-year-selpars-autocor).
    
Le `r wchgs` a été supprimé (il a également été supprimé dans le `r la`) car il avait peu d'effet sur la biomasse et les estimations de sélectivité étaient médiocres (Figure \@ref(fig:bridge-biomass-group3)). Le résultat a été une trajectoire de biomasse réduite, avec une biomasse relative similaire à celle du modèle précédent.

Les estimations de la mortalité naturelle du modèle à ce stade étaient `r bvals[[3]][[2]]$m_male[1]` pour les mâles et `r bvals[[3]][[2]]$m_female[1]` pour les femelles, avec des intervalles crédibles de `r bvals[[3]][[2]]$m_male[2]` et `r bvals[[3]][[2]]$m_female[2]`, respectivement. L'estimation de la mortalité naturelle des femelles était proche de la valeur fixée pour les femelles dans les évaluations réalisées dans les juridictions voisines (0,20), mais l'estimation des mâles était beaucoup plus faible que celle utilisée dans les stocks voisins (0,35). Sur la base des valeurs estimées de la mortalité naturelle et de la forte corrélation entre les paramètres estimés pour ce modèle (Figure \@ref(fig:fig-bridge10-pairs)), nous avons décidé de fixer les mortalités naturelles aux mêmes valeurs que les évaluations du Golfe de l'Alaska et de la Mer de Béring et des Iles Aléoutiennes [@goa2021; @goa2020; @goa2019; @bering2019]; 0,20 pour les femelles et 0,35 pour les mâles.
")
```
