```{r scam-sensitivity-analyses-en, eval = !fr(), results = 'asis'}
cat("## SENSITIVITY ANALYSES {#sens-analyses}
We tested sensitivity of the model outputs as follows:

1. Decrease $\sigma$  from `r base_sig` to `r sens_1_2_sig` (changes $\vartheta^2$ and $\rho$) and estimate $\vartheta^2$
1. Increase initial value of $\tau$ from `r base_tau` to `r sens_1_3_tau` (changes $\vartheta^2$ and $\rho$) and estimate $\vartheta^2$
1. Decrease initial value of $\tau$ from `r base_tau` to `r sens_1_4_tau` (changes $\vartheta^2$ and $\rho$) and estimate $\vartheta^2$
1. Decrease mean of $h$ prior from `r f(base_h_prior1,  2)` to `r f(sens_1_5_h_prior1, 2)`
1. Estimate $M_\mathrm{female}$ with a narrow prior (SD = `r sens_2_2_m_female$p2`)
1. Estimate $M_\mathrm{female}$ with a broad prior (SD = `r sens_2_3_m_female$p2`)
1. Estimate $M_\mathrm{male}$ with a narrow prior (SD = `r sens_2_4_m_male$p2`)
1. Estimate $M_\mathrm{male}$ with a broad prior (SD = `r sens_2_5_m_male$p2`)
1. Increase mean of priors for catchabilities from `r base_qk_mean` to `r sens_qk_mean` ($q_k$ for all gears $k$)
1. Broader catchability priors, from SD = `r base_qk_sd` to `r sens_qkp_sd` ($q_k$ for all gears $k$)
1. Selectivity curves equal maturity ogive for all gears
1. Estimate time-varying selectivity for the `r qcs`, to try to improve the survey index fit
1. Geostatistical model-based survey indices (Section \@ref(app:geostat))
1. Remove Discard CPUE
1. Modify maturity ogive to not include 'developing' or 'resting' specimens
1. Fix selectivity for the Discard CPUE index to be equal to the Shoreside fishery selectivity
1. Fix all survey's selectivity to be equal to the Shoreside fishery selectivity

This list of sensitivity scenarios with more details is provided in Table \@ref(tab:sens-param-settings-table). Base model parameter settings are provided in Table \@ref(tab:param-settings-table). All sensitivity models were run using MCMC with a chain length of `r f(mcmc_chain_length)`, a sample frequency of `r f(mcmc_sample_freq)`, giving `r f(mcmc_num_samples)` samples, which were then burned in by `r f(mcmc_burn_in)` giving a total of `r f(mcmc_actual_samples)` samples retained for inference.
")
```

```{r scam-sensitivity-analyses-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## ANALYSES DE SENSIBILITÉ {#sens-analyses}
Nous avons testé la sensibilité des résultats du modèle comme suit :

1. Diminuer $\sigma$ de `r base_sig` à `r sens_1_2_sig` (change $\vartheta^2$ et $\rho$) et estimer $\vartheta^2$.
1. Augmenter la valeur initiale de $\tau$ de `r base_tau` à `r sens_1_3_tau` (modifie $\vartheta^2$ et $\rho$) et estimer $\vartheta^2$.
1. Diminuer la valeur initiale de $\tau$ de `r base_tau` à `r sens_1_4_tau` (modifie $\vartheta^2$ et $\rho$) et estimer $\vartheta^2$.
1. Diminuer la moyenne de l'a priori $h$ de `r f(base_h_prior1, 2)` à `r f(sens_1_5_h_prior1, 2)`
1. Estimer $M_\mathrm{femme}$ avec un a priori étroit (SD = `r sens_2_2_m_female$p2`)
1. Estimation de $M_\mathrm{femme}$ avec un a priori large (SD = `r sens_2_3_m_female$p2`)
1. Estimation de $M_\mathrm{masculin}$ avec un a priori étroit (SD = `r sens_2_4_m_male$p2`)
1. Estimation de $M_\mathrm{male}$ avec un a priori large (SD = `r sens_2_5_m_male$p2`)
1. Augmenter la moyenne des a priori pour les capturabilités de `r base_qk_mean` à `r sens_qk_mean` ($q_k$ pour tous les engins $k$)
1. A priori de capturabilité plus large, de SD = `r base_qk_sd` à `r sens_qkp_sd` ($q_k$ pour tous les engins $k$)
1. Courbes de sélectivité égales à l'ogive de maturité pour tous les engins
1. Estimer la sélectivité variable dans le temps pour les `r qcs`, afin d'essayer d'améliorer l'ajustement de l'indice d'enquête
1. Indices d'enquête basés sur un modèle géostatistique (Section \@ref(app:geostat))
1. Supprimer la CPUE des rejets
1. Modifier l'ogive de maturité pour ne pas inclure les spécimens 'en développement' ou 'au repos'.
1. Fixer la sélectivité de l'indice DCPUE à un niveau égal à la sélectivité de la pêcherie côtière.
1. Fixer la sélectivité de toutes les enquêtes pour qu'elle soit égale à la sélectivité de la pêche côtière.

Cette liste de scénarios de sensibilité, avec plus de détails, est fournie dans le tableau \@ref(tab:sens-param-settings-table). Les paramètres du modèle de base sont indiqués dans le tableau \@ref(tab:param-settings-table). Tous les modèles de sensibilité ont été exécutés à l'aide de MCMC avec une longueur de chaîne de `r f(mcmc_chain_length)`, une fréquence d'échantillonnage de `r f(mcmc_sample_freq)`, donnant `r f(mcmc_num_samples)` échantillons, qui ont ensuite été brûlés par `r f(mcmc_burn_in)` donnant un total de `r f(mcmc_actual_samples)` échantillons retenus pour l'inférence.")
```

```{r scam-sens-sigma-en, eval = !fr(), results = 'asis'}
cat("### Decreasing $\sigma$ and adjusting $\tau$ {#sens-sigma}
`r iscam` uses an error parameterization which includes two parameters, $\vartheta^2$ and $\rho$. They represent the total variance and the proportion of total variance associated with observation errors, respectively [@iscam]. Observation error SD ($\sigma$) and process error SD ($\tau$) cannot be estimated directly, instead there is a calculation done to translate those values to and from $\vartheta^2$ and $\rho$ (Appendix \@ref(app:model-desc), Eq. \@ref(eq:df17)). The values of $\sigma$ and $\tau$ were fixed in the base model [@grandin2017] at `r base_sig` and `r base_tau` respectively. By calculation, $\vartheta^2$ and $\rho$ were fixed at `r f(base_vartheta$init, 2)` and `r f(base_rho$init, 4)`.

Reducing the observation error by decreasing $\sigma$ from `r base_sig` to `r sens_1_2_sig` and estimating $\vartheta^2$ increased the value of $\vartheta^2$ from `r f(base_vartheta$init, 2)` to `r f(sens_1_2_vartheta$init, 2)` while approximately halving $\rho$ from `r f(base_rho$init, 3)` to `r f(sens_1_2_rho$init, 3)`. The median and 95% CI of the posterior for $\vartheta^2$ was `r sens_1_2_vartheta$est`. There was little effect on the absolute biomass trajectory (Figure \@ref(fig:fig-sens-variance)), but the estimate of $B_0$ was increased from `r f(as.numeric(base_sbo[1]) * 1000)`, to `r svals[[1]][[2]]$sbo[1]`,000 t (Figure \@ref(fig:fig-sens-variance)). The increase in the $B_0$ estimate caused a scaling downward of the relative biomass trajectory (Figure \@ref(fig:fig-sens-variance-rel)). There were no substantial changes to the index fits, age fits, or selectivities.

Setting the value for $\tau$ to `r sens_1_3_tau` had a similar effect to reducing the assumed index observation error and lowered the relative biomass trajectory. For this value of $\tau$, the values of $\vartheta^2$ and $\rho$ were `r f(sens_1_3_vartheta$init, 2)` and `r f(sens_1_3_rho$init, 3)` respectively (Appendix \@ref(app:model-desc), Eq. \@ref(eq:df17)).

Setting the initial value for $\tau$ to `r sens_1_4_tau` also had little effect on absolute biomass. For this value of $\tau$, the initial values of $\vartheta^2$ and $\rho$ were `r f(sens_1_4_vartheta$init, 2)` and `r f(sens_1_4_rho$init, 3)` respectively. The estimate for $\vartheta^2$ was `r sens_1_4_vartheta$est`.

The estimates of $B_0$ were increased for both of these models when compared to the base model, which resulted in scaling down of the relative biomass trajectory and putting the status in 2021/2022 to be estimated just below the LRP for the $\tau = 1.0$ model and just below the USR for the $\tau = 0.6$ model (Figure \@ref(fig:fig-sens-variance-rel)). The increase of $B_0$ was much greater, and had a much larger CI for the $\tau = 1.0$ model when compared to the $\tau = 0.6$ model.

### Decreasing the mean of the steepness prior {#sens-h}

Decreasing the steepness prior mean from `r f(base_h_prior1, 2)` to `r f(sens_1_5_h_prior1, 2)` and changing the prior SD from `r f(base_h_prior2, 2)` to `r f(sens_1_5_h_prior2, 2)` produced little change in both absolute biomass and $B_0$ (Figure \@ref(fig:fig-sens-variance)), despite having a different posterior (Figure \@ref(fig:sens-steepness-prior), compare to base model Figure \@ref(fig:fig-base-priors-posts)). The prior for $h$ is very influential on the posterior, but the value of $h$ does not have a large effect on the absolute or relative biomass (Figure \@ref(fig:fig-sens-variance-rel)).
")
```

```{r scam-sens-sigma-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Diminution de $\sigma$ et ajustement de $\tau$ {#sens-sigma}
`r iscam` utilise un paramétrage d'erreur qui comprend deux paramètres, $\vartheta^2$ et $\rho$. Ils représentent respectivement la variance totale et la proportion de la variance totale associée aux erreurs d'observation [@iscam]. L'erreur d'observation SD ($\sigma$) et l'erreur de processus SD ($\tau$) ne peuvent pas être estimées directement, mais un calcul est effectué pour convertir ces valeurs en $\vartheta^2$ et $\rho$ (Annexe \@ref(app:model-desc), Eq. \@ref(eq:df17)). Les valeurs de $\sigma$ et $\tau$ ont été fixées dans le modèle de base [@grandin2017] à `r base_sig` et `r base_tau` respectivement. Par calcul, $\vartheta^2$ et $\rho$ ont été fixés à `r f(base_vartheta$init, 2)` et `r f(base_rho$init, 4)`.

La réduction de l'erreur d'observation en diminuant $\sigma$ de `r base_sig` à `r sens_1_2_sig` et l'estimation de $\vartheta^2$ ont augmenté la valeur de $\vartheta^2$ de `r f(base_vartheta$init, 2)` à `r f(sens_1_2_vartheta$init, 2)` tout en réduisant de moitié environ $\rho$ de `r f(base_rho$init, 3)` à `r f(sens_1_2_rho$init, 3)`. La médiane et l'IC à 95 % de la valeur postérieure pour $\vartheta^2$ étaient `r sens_1_2_vartheta$est`. Il y a eu peu d'effet sur la trajectoire de la biomasse absolue (figure \@ref(fig:fig-sens-variance)), mais l'estimation de $B_0$ a été augmentée de `r f(as.numeric(base_sbo[1]) * 1000)`, à `r svals[[1]][[2]]$sbo[1]`,000 t (figure \@ref(fig:fig-sens-variance)). L'augmentation de l'estimation $B_0$ a entraîné une réduction de l'échelle de la trajectoire de la biomasse relative (figure \@ref(fig:fig-sens-variance-rel)). Il n'y a pas eu de changements substantiels dans les ajustements de l'indice, les ajustements de l'âge ou les sélectivités.

Le fait de fixer la valeur de $\tau$ à `r sens_1_3_tau` a eu un effet similaire à la réduction de l'erreur d'observation supposée de l'indice et a abaissé la trajectoire de la biomasse relative. Pour cette valeur de $\tau$, les valeurs de $\vartheta^2$ et $\rho$ étaient respectivement `r f(sens_1_3_vartheta$init, 2)` et `r f(sens_1_3_rho$init, 3)` (Annexe \@ref(app:model-desc), Eq. \@ref(eq:df17)).

Le fait de fixer la valeur initiale de $\tau$ à `r sens_1_4_tau` a également eu peu d'effet sur la biomasse absolue. Pour cette valeur de $\tau$, les valeurs initiales de $\vartheta^2$ et $\rho$ étaient respectivement `r f(sens_1_4_vartheta$init, 2)` et `r f(sens_1_4_rho$init, 3)`. L'estimation de $\vartheta^2$ était `r sens_1_4_vartheta$est`.

Les estimations de $B_0$ ont augmenté pour ces deux modèles par rapport au modèle de base, ce qui a entraîné une réduction de la trajectoire de la biomasse relative et une estimation de l'état en 2021/2022 proche du PRL (figure \@ref(fig:fig-sens-variance-rel)). L'augmentation de $B_0$ était beaucoup plus importante et avait un IC plus grand pour le modèle $\tau = 1.0$ que pour le modèle $\tau = 0.6$ (`r sens_1_3_sbo$est` vs. `r sens_1_4_sbo$est`) en milliers de tonnes.

### Diminution de la moyenne de l'a priori de pente {#sens-h}

La diminution de la moyenne de l'a priori de pente de `r f(base_h_prior1, 2)` à `r f(sens_1_5_h_prior1, 2)` et la modification de l'a priori SD de `r f(base_h_prior2, 2)` à `r f(sens_1_5_h_prior2, 2)` ont produit peu de changement à la fois dans la biomasse absolue et $B_0$ (Figure \@ref(fig:fig-sens-variance)), malgré un a priori différent (Figure \@ref(fig:sens-steepness-prior), par rapport au modèle de base Figure \@ref(fig:fig-base-priors-posts)). L'a priori pour $h$ est très influent sur le postérieur, mais la valeur de $h$ n'a pas un grand effet sur la biomasse absolue ou relative (Figure \@ref(fig:fig-sens-variance-rel)).")
```

```{r scam-sens-m-en, eval = !fr(), results = 'asis'}
cat("### Modifying priors on $M_\mathrm{female}$ and $M_\mathrm{male}$ {#sens-m}
In the base model, the natural mortality parameters $M_\mathrm{female}$ and $M_\mathrm{male}$ are fixed to `r f(exp(base_m_female$init), 2)` and `r f(exp(base_m_male$init), 2)` respectively. Four sensitivity models were run, to estimate each $M$ parameter with broad and narrow prior SDs. Figure \@ref(fig:fig-sens-m) shows the absolute biomass trajectories for these models. The relative spawning biomass trajectories are shown in Figure \@ref(fig:fig-sens-m-rel). Estimating $M_\mathrm{female}$ with narrow and broad priors produced estimates for $M_\mathrm{female}$ of `r sens_2_2_m_female$est` and `r sens_2_3_m_female$est` respectively. $M_\mathrm{male}$ remained fixed for those models, at `r f(exp(base_m_male$init), 2)`. Figure \@ref(fig:fig-sens-m) shows that the model is sensitive to the female natural mortality parameter, as both absolute biomass trajectories and $B_0$ estimates are inflated. The estimates are quite different from the fixed value of `r f(exp(base_m_female$init), 2)`, causing this scaling effect. If the female mortality is higher, the model must adjust the starting point ($B_0$) higher in order to fit all parameters including the indices with the drop in biomass in 2019 (Figure \@ref(fig:fig-base-index-fits)).

The sensitivity models that estimate $M_\mathrm{male}$ with narrow and broad priors produced estimates of `r sens_2_4_m_male$est` and `r sens_2_5_m_male$est` respectively. These estimates were also substantially different than the fixed values of the parameter (`r f(exp(base_m_male$init), 2)`). However, males only make up `r f((1 - as.numeric(total_prop_female)) * 100)`% of the spawning stock biomass and estimated male selectivity is generally farther to the right of maturity than females (Figure \@ref(fig:fig-base-mcmc-selex)). This implies that males removed from the stock will have lower overall impact to the stock biomass, since there are not as many older male fish in the stock to be caught, and the selectivity is higher on those fewer fish. The lack of older males can be seen in the length and age data (Figures \@ref(fig:fig-lengths) and \@ref(fig:fig-ages)).

This model is sensitive to natural mortality values whether fixed or estimated. The base model uses fixed values as used by several nearby jurisdictions [@goa2017; @goa2019; @bering2019; @goa2020; @goa2021].
")
```

```{r scam-sens-m-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Modifier les priors sur $M_\mathrm{femelle}$ et $M_\mathrm{mâle}$ {#sens-m}
Dans le modèle de base, les paramètres de mortalité naturelle $M_\mathrm{femme}$ et $M_\mathrm{mâle}$ sont fixés à `r f(exp(base_m_female$init), 2)` et `r f(exp(base_m_male$init), 2)` respectivement. Quatre modèles de sensibilité ont été exécutés pour estimer chaque paramètre de $M$ avec des écarts types larges et étroits. La figure \@ref(fig:fig-sens-m) montre les trajectoires de biomasse absolue pour ces modèles. Les trajectoires relatives de la biomasse de frai sont présentées dans la figure \@ref(fig:fig-sens-m-rel). L'estimation de $M_\mathrm{femelle}$ avec des a priori étroits et larges a produit des estimations pour $M_\mathrm{femelle}$ de `r sens_2_2_m_female$est` et `r sens_2_3_m_female$est` respectivement. $M_\mathrm{mâle}$ est resté fixe pour ces modèles, à `r f(exp(base_m_male$init), 2)`. La figure \@ref(fig:fig-sens-m) montre que le modèle est sensible au paramètre de mortalité naturelle des femelles, car les trajectoires de biomasse absolue et les estimations de $B_0$ sont gonflées. Les estimations sont très différentes de la valeur fixe de `r f(exp(base_m_female$init), 2)`, ce qui provoque cet effet d'échelle. Si la mortalité des femelles est plus élevée, le modèle doit ajuster le point de départ ($B_0$) à la hausse afin d'ajuster tous les paramètres, y compris les indices, à la baisse de la biomasse en 2019 (figure \@ref(fig:fig-base-index-fits)).

Les modèles de sensibilité qui estiment $M_\mathrm{male}$ avec des a priori étroits et larges ont produit des estimations de `r sens_2_4_m_male$est` et `r sens_2_5_m_male$est` respectivement. Ces estimations sont également très différentes des valeurs fixes du paramètre (`r f(exp(base_m_male$init), 2)`). Cependant, les mâles ne représentent que `r f((1 - as.numeric(total_prop_female)) * 100)`% de la biomasse du stock reproducteur et la sélectivité estimée des mâles est généralement plus à droite de la maturité que celle des femelles (Figure \@ref(fig:fig-base-mcmc-selex)). Cela implique que les mâles retirés du stock auront un impact global plus faible sur la biomasse du stock, étant donné qu'il n'y a pas autant de poissons mâles plus âgés dans le stock à capturer, et que la sélectivité est plus élevée pour ces poissons moins nombreux. Le manque de mâles plus âgés est visible dans les données relatives à la longueur et à l'âge (figures \@ref(fig:fig-lengths) et \@ref(fig:fig-ages)).

Ce modèle est sensible aux valeurs de mortalité naturelle, qu'elles soient fixes ou estimées. Le modèle de base utilise les valeurs fixes utilisées par plusieurs juridictions voisines [@goa2017; @goa2019; @bering2019; @goa2020; @goa2021].")
```

```{r scam-sens-q-en, eval = !fr(), results = 'asis'}
cat("### Modifying catchability priors {#sens-q}
The catchability parameters are $\operatorname{ln}(q_k)$ where $k$ is the gear, one for each trawl fleet and survey index (`r paste(base_model$dat$gear_names, collapse = ', ')`). These parameters have an associated normal prior with a log mean and SD set in the `r iscam` control files. In the base model those are `r paste0('$\operatorname{ln}(', f(base_qk_mean, 1), ')$')` and `r paste0('$', f(base_qk_sd, 1), '$')`, respectively.

Two sensitivity models were run to test the influence of the priors for $\operatorname{ln}(q_k)$. In the first, the means for all gears were increased from `r paste0('$\operatorname{ln}(', f(base_qk_mean, 1), ')$')` to `r paste0('$\operatorname{ln}(', f(sens_qk_mean, 1), ')$')`, and the SD remained at `r paste0('$', f(base_qk_sd, 1), '$')`. In the second, the prior was broadened by setting the SD for all the gears to `r paste0('$', f(base_qk_sd, 1), '$')`. The means for that model remained at `r paste0('$\operatorname{ln}(', f(base_qk_mean, 1), ')$')`.

The absolute and relative biomasses were almost identical to the base model for these models (Figures \@ref(fig:fig-sens-q-m) and \@ref(fig:fig-sens-q-rel)). The catchability estimates were also almost identical between these models and the base model (Figure \@ref(fig:fig-sens-q-q)).
")
```

```{r scam-sens-q-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Modifier les paramètres de capturabilité {#sens-q}
Les paramètres de capturabilité sont $\operatorname{ln}(q_k)$ où $k$ est l'engin, un pour chaque flottille de chalutage et indice d'enquête (`r paste(base_model$dat$gear_names, collapse = ', ')`). Ces paramètres ont un a priori normal associé avec une moyenne logarithmique et un écart-type définis dans les fichiers de contrôle `r iscam`. Dans le modèle de base, ces paramètres sont respectivement `r paste0('$\operatorname{ln}(', f(base_qk_mean, 1), ')$')` et `r paste0('$', f(base_qk_sd, 1), '$')`.

Deux modèles de sensibilité ont été exécutés afin de tester l'influence des prières pour $\operatorname{ln}(q_k)$. Dans le premier, les moyennes pour tous les engins ont été augmentées de `r paste0('$\operatorname{ln}(', f(base_qk_mean, 1), ')$')` à `r paste0('$\operatorname{ln}(', f(sens_qk_mean, 1), ')$')`, et le SD est resté à `r paste0('$', f(base_qk_sd, 1), '$')`. Dans le second, l'a priori a été élargi en fixant l'écart-type pour tous les engrenages à `r paste0('$', f(base_qk_sd, 1), '$')`. Les moyennes pour ce modèle sont restées à `r paste0('$\operatorname{ln}(', f(base_qk_mean, 1), ')$')`.

La biomasse absolue et relative était presque identique au modèle de base pour ces modèles (figures \@ref(fig:fig-sens-q-m) et \@ref(fig:fig-sens-q-rel)). Les estimations de la capturabilité étaient également presque identiques entre ces modèles et le modèle de base (figure \@ref(fig:fig-sens-q-q)).
")
```

```{r scam-sens-sel-mat-en, eval = !fr(), results = 'asis'}
cat("### Setting selectivities equal to maturity {#sens-sel-mat}
This sensitivity came about in the `r la` cycle, where it was found that the estimated selectivity curves were all to the right of the maturity ogive [Figure 17, @grandin2017]. This caused the value of $F_\mathrm{MSY}$ to be very large and essentially give the advice that an unlimited amount of catch could be taken without affecting the stock. We repeat it here, as the same situation has arisen with the current base model and to compare this model with the single sex model from the `r la`.

For this model structure, the absolute biomass and $B_0$ estimates are much larger than for the base model (Figure \@ref(fig:fig-sens-selex)). The median of the posterior for $B_0$ was estimated to be `r f(as.numeric(svals[[4]][[2]]$sbo[1]) * 1000)` t with a broad CI of `r svals[[4]][[2]]$sbo[2]` thousand t. For comparison, the base model had a $B_0$ estimate of `r f(as.numeric(base_sbo[1]) * 1000)` t with a CI of `r base_sbo[2]` thousand t. The absolute biomass trajectory is also high, so the relative biomass is higher than the base model (Figure \@ref(fig:fig-sens-selex-rel)). The index fits all reflect this, as they all show a one-way trip downwards (Figure \@ref(fig:fig-sens-selex-index-fits)).

The vulnerable biomass for this model is substantially higher than for the base model (Figure \@ref(fig:fig-sens-sel-eq-mat-vuln)), and exactly equal for the two fleets (one is overlapping the other and we cannnot see it in the figure). This is due to selectivity being exactly the same for both fleets, not because they are equal to the maturity. The ratio of the sum of the two fleets' vulnerable biomasses to the spawning biomass is `r f(sel_eq_mat_vuln_ratio, 2)`. For the base model, this ratio is `r f(base_model_vuln_ratio, 2)`. Moving the selectivity to the left increases the vulnerable biomass relative to the spawning biomass.
")
```

```{r scam-sens-sel-mat-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Fixer des sélectivités égales à la maturité {#sens-sel-mat}
Cette sensibilité est apparue lors du cycle `r la`, où l'on a constaté que les courbes de sélectivité estimées étaient toutes à droite de l'ogive de maturité [Figure 17, @grandin2017]. De ce fait, la valeur de $F_\mathrm{MSY}$ était très élevée et donnait essentiellement à penser qu'un nombre illimité de captures pouvait être effectué sans affecter le stock. Nous le répétons ici, car la même situation s'est produite avec le modèle de base actuel et pour comparer ce modèle avec le modèle à sexe unique de la `r la`.

Pour cette structure de modèle, les estimations absolues de biomasse et de $B_0$ sont beaucoup plus importantes que pour le modèle de base (Figure \@ref(fig:fig-sens-selex)). La médiane de la valeur postérieure de $B_0$ a été estimée à `r f(as.numeric(svals[[4]][[2]]$sbo[1]) * 1000)` t avec un IC large de `r svals[[4]][[2]]$sbo[2]` mille t. À titre de comparaison, le modèle de base avait une estimation de $B_0$ de `r f(as.numeric(base_sbo[1]) * 1000)` t avec un IC de `r base_sbo[2]` mille t. La trajectoire de la biomasse absolue est également élevée, de sorte que la biomasse relative est supérieure à celle du modèle de base (Figure \@ref(fig:fig-sens-selex-rel)). Les ajustements de l'indice reflètent tous cela, puisqu'ils montrent tous un aller simple vers le bas (Figure \@ref(fig:fig-sens-selex-index-fits)).

La biomasse vulnérable de ce modèle est nettement plus élevée que celle du modèle de base (figure \@ref(fig:fig-sens-sel-eq-mat-vuln)), et exactement égale pour les deux flottes (l'une chevauche l'autre, ce qui n'est pas visible sur la figure). Cela est dû au fait que la sélectivité est exactement la même pour les deux flottes, et non pas au fait qu'elles sont égales à la maturité. Le rapport entre la somme des biomasses vulnérables des deux flottes et la biomasse de frai est `r f(sel_eq_mat_vuln_ratio, 2)`. Pour le modèle de base, ce rapport est `r f(base_model_vuln_ratio, 2)`. En déplaçant la sélectivité vers la gauche, on augmente la biomasse vulnérable par rapport à la biomasse reproductrice.
")
```

```{r scam-sens-qcs-tv-en, eval = !fr(), results = 'asis'}
cat("### Using TV selectivity for the `r qcs` {#sens-qcs-tv}
In an attempt to improve the fit of the `r qcs` index (Figure \@ref(fig:fig-base-index-fits)), we implemented time-varying selectivity in `r iscam` and ran the model with the `r qcs` having three blocks of selectivity, 2003--2010, 2011--2016, and 2017--2021. We tried many combinations of both number of selectivity blocks and range of each block and this particular combination fit the data the best.

The absolute and relative biomasss trajectories both show a lower value in 2022 than the base model (Figures \@ref(fig:fig-sens-selex) and \@ref(fig:fig-sens-selex-rel)). The index fit was better overall than for the base model, especially in the latter part of the series (Figure \@ref(fig:fig-sens-selex-index-fits)). The improved fit to the QCS index was the goal of this sensitivity run but came at the expense of poor estimates of selectivity. The selectivity estimates for the three-year blocks can be seen in Figure \@ref(fig:fig-sens-qcs-tv). The male selectivity for the early years (left panel) is far to the right, much further than the time-invariant selectivities in the base model (Figure \@ref(fig:fig-base-mcmc-selex)). The other two time periods have even more unreasonable estimates of selectivity, making this model unusable for any form of advice.

There was also some autocorrelation in the MCMC samples for the `r qcs` selectivity parameters in this model (Figure \@ref(fig:fig-sens-qcs-autocor-sel)) and the trace plots for those parameters are not adequate for valid inference (Figure \@ref(fig:fig-sens-qcs-trace-sel-tv)).
")
```

```{r scam-sens-qcs-tv-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Utilisation de la sélectivité TV pour le `r qcs` {#sens-qcs-tv}
Afin d'améliorer l'ajustement de l'indice `r qcs` (Figure \@ref(fig:fig-base-index-fits)), nous avons implémenté une sélectivité variable dans le temps dans `r iscam` et avons exécuté le modèle avec le `r qcs` ayant trois blocs de sélectivité, 2003--2010, 2011--2016, et 2017--2021. Nous avons essayé de nombreuses combinaisons du nombre de blocs de sélectivité et de l'étendue de chaque bloc, et c'est cette combinaison particulière qui s'est le mieux adaptée aux données.

Les trajectoires de la biomasse absolue et relative montrent toutes deux une valeur inférieure en 2022 à celle du modèle de base (figures \@ref(fig:fig-sens-selex) et \@ref(fig:fig-sens-selex-rel)). L'ajustement de l'indice était globalement meilleur que pour le modèle de base, en particulier dans la dernière partie de la série (figure \@ref(fig:fig-sens-selex-index-fits)). L'amélioration de l'ajustement de l'indice QCS était l'objectif de cette exécution du modèle, mais elle s'est faite aux dépens de mauvaises estimations de la sélectivité. Les estimations de la sélectivité pour les blocs de trois ans sont présentées dans la figure \@ref(fig:fig-sens-qcs-tv). La sélectivité masculine pour les premières années (panneau de gauche) est très à droite, bien plus loin que les sélectivités invariantes dans le temps du modèle de base (figure \@ref(fig:fig-base-mcmc-selex)). Les deux autres périodes présentent des estimations encore plus déraisonnables de la sélectivité, ce qui rend ce modèle inutilisable pour toute forme de conseil.

Il y avait également une certaine autocorrélation dans les échantillons MCMC pour les paramètres de sélectivité `r qcs` dans ce modèle (Figure \@ref(fig:fig-sens-qcs-autocor-sel)) et les tracés pour ces paramètres ne sont pas adéquats pour une inférence valide (Figure \@ref(fig:fig-sens-qcs-trace-sel-tv)).
")
```

```{r scam-sens-geostat-en, eval = !fr(), results = 'asis'}
cat("### Using survey indices calculated using geostatistical modelling {#sens-geostat}
This sensitivity case involved replacing the index data for the three synoptic surveys: (`r qcs`, `r hss`, and `r wcvis`). These data are calculated using a standard design-based estimator in the base model. Here, they were replaced with geostatistical-based indices (Appendix \@ref(app:geostat)). Both absolute and relative biomass are similar to the base model, with a slightly higher estimate of $B_0$ and a slightly higher absolute biomass trajectory (Figures \@ref(fig:fig-sens-geostat) and \@ref(fig:fig-sens-geostat-rel)).

The index fit is shown in Figure \@ref(fig:fig-sens-geostat-index-fits). The fit to the geostatistical-based index is approximately visually equivalent to the fit to the index in the base model (Figure \@ref(fig:fig-base-index-fits)) but they are not shown on the same plot together due to the base indices being different.
")
```

```{r scam-sens-geostat-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Utilisation d'indices d'enquête calculés à l'aide de la modélisation géostatistique {#sens-geostat}
Ce cas de sensibilité implique le remplacement des données d'index pour les trois enquêtes synoptiques (`r qcs`, `r hss`, et `r wcvis`). Ces données sont calculées à l'aide d'un estimateur standard dans le modèle de base. Ici, elles ont été remplacées par des indices basés sur la géostatistique (annexe \@ref(app:geostat)). La biomasse absolue et relative est similaire au modèle de base, avec une estimation légèrement plus élevée de $B_0$ et une trajectoire de biomasse absolue légèrement plus élevée (Figures \@ref(fig:fig-sens-geostat) et \@ref(fig:fig-sens-geostat-rel)).

L'ajustement de l'indice est présenté dans la figure \@ref(fig:fig-sens-geostat-index-fits). L'ajustement de l'indice basé sur la géostatistique est approximativement équivalent visuellement à l'ajustement de l'indice dans le modèle de base (Figure \@ref(fig:fig-base-index-fits)) mais ils ne sont pas montrés sur le même graphique ensemble en raison des indices de base qui sont différents.
")
```

```{r scam-sens-remove-discard-cpue-en, eval = !fr(), results = 'asis'}
cat("### Removal of the Discard CPUE index from the model {#sens-remove-dcpue}
We tested the impact of removing the Discard CPUE index. The relative biomass trajectory remained similar, with only a slight increase in end year biomass and slightly lower overall relative biomass (Figure \@ref(fig:fig-sens-meeting-rel)). The fits for the survey indices showed only minor departures from the base model fits (Figure \@ref(fig:fig-sens-remove-dcpue-index-fits)).
")
```

```{r scam-sens-remove-discard-cpue-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Suppression de l'indice de CPUE de rejets du modèle {#sens-remove-dcpue}
Nous avons testé l'impact de la suppression de l'indice de CPUE des rejets. La trajectoire de la biomasse relative est restée similaire, avec seulement une légère augmentation de la biomasse de fin d'année et une biomasse relative globale légèrement inférieure (Figure \@ref(fig:fig-sens-meeting-rel)). Les ajustements pour les indices de l'enquête n'ont montré que des écarts mineurs par rapport aux ajustements du modèle de base (Figure \@ref(fig:fig-sens-remove-dcpue-index-fits)).
")
```

```{r scam-sens-change-maturity-en, eval = !fr(), results = 'asis'}
cat("### Modification of the maturity ogive {#sens-change-maturity}
`r sp` spawn during the winter, and the surveys take place during the summer. Many of the maturities recorded in the summer are therfore in the 'resting' phase which can be difficult to distinguish from immature. There is also some ambiguity in the classification of 'developing' fish (codes 2 and 3 in the DFO maturity codes for flatfish).

Removing 'developing' and resting' from the maturity ogive produced a better-fitting ogive (Figure \@ref(fig:fig-mat)) and resulted in slightly lower overall $B_0$ estimate and absolute biomass compared to the base model, which resulted in a similar relative biomass (Figures \@ref(fig:fig-sens-meeting) and \@ref(fig:fig-sens-meeting-rel)). This maturity should be considered for the base model in the next assessment. Since it made no qualitative difference on the results, and because it was worked up following the initial review meeting, we did not include it in the base model for this assessment.

The biomass vulnerable to the two fleets compared to the spawning biomass is shown in Figure \@ref(fig:fig-sens-meeting-vuln). The vulnerable biomass is lwoer for each fleet than the spawning biomass, as it should be when only the mature portion of the stock is available to catch.
")
```

```{r scam-sens-change-maturity-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Modification de l'ogive de maturité {#sens-change-maturity}
`r sp` frayent pendant l'hiver et les enquêtes ont lieu pendant l'été. De nombreuses maturités enregistrées en été sont donc en phase de 'repos', ce qui peut être difficile à distinguer de l'immaturité. Il existe également une certaine ambiguïté dans la classification des poissons 'en développement' (codes 2 et 3 dans les codes de maturité du MPO pour les poissons plats).

La suppression des phases de 'développement' et de 'repos' de l'ogive de maturité a produit une ogive mieux ajustée (figure \@ref(fig:fig-mat)) et a entraîné une biomasse absolue de l'année finale légèrement inférieure à celle du modèle de base, mais la même biomasse relative (figures \@ref(fig:fig-sens-meeting) et \@ref(fig:fig-sens-meeting-rel)). Cette maturité devrait être prise en compte dans le modèle de base de la prochaine évaluation. Étant donné qu'elle n'a pas eu d'incidence qualitative sur les résultats et qu'elle a été élaborée à la suite de la réunion d'examen initiale, nous ne l'avons pas incluse dans le modèle de base pour la présente évaluation.
")
```

```{r scam-sens-fix-selectivities-en, eval = !fr(), results = 'asis'}
cat("### Fixing selectivities {#sens-fix-selectivities}
There were two sensitivities for which selectivities were fixed to the estimated value of the shoreside fishery in the base model:

1. Fix selectivity of the Discard CPUE index to the shoreside fishery selectivity
1. Fix selectivity of all surveys to the shoreside fishery selectivity

Fixing the Discard CPUE selectivity resulted in a slightly lower absolute and relative biomass for the final year compared to the base model. There were no substantial index fit differences.

Fixing the survey selectivities produced a large change in the model, with a much higher $B_0$ estimate (Figure \@ref(fig:fig-sens-meeting)) resulting in a large scaling down in relative biomass (Figure \@ref(fig:fig-sens-meeting-rel)). There was also a pronounced upward swing in biomass at the end of the time series implying sudden exponential growth of the stock, which is an unrealistic outcome. The index fits were slightly different with this model, with a pronounced lower estimate for the `r qcsss` in 2010.
")
```

```{r scam-sens-fix-selectivities-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("### Fixation des sélectivités {#sens-fix-selectivities}
Il y a eu deux sensibilités pour lesquelles les sélectivités ont été fixées à la valeur estimée de la pêche côtière dans le modèle de base:

1. Fixer la sélectivité de l'indice DCPUE à la sélectivité de la pêche à terre
1. Fixer la sélectivité de toutes les enquêtes à la sélectivité de la pêche côtière

La fixation de la sélectivité de l'indice DCPUE a entraîné une biomasse absolue et relative légèrement inférieure à celle du modèle de base. Il n'y a pas eu de différences substantielles dans l'ajustement de l'indice.

La fixation des sélectivités des campagnes a entraîné un changement important dans le modèle, avec une estimation $B_0$ beaucoup plus élevée (Figure \@ref(fig:fig-sens-meeting)) entraînant une forte réduction de la biomasse relative (Figure \@ref(fig:fig-sens-meeting-rel)). Il y a également eu une forte augmentation de la biomasse à la fin de la série chronologique, ce qui implique une croissance exponentielle du stock, ce qui n'est pas réaliste. Les ajustements de l'indice étaient légèrement différents avec ce modèle, avec une différence d'ajustement prononcée pour le `r qcsss`.
")
```
