```{r appendix-prop-para-1-en, eval = !fr(), results = 'asis'}
cat("# PROPORTION FEMALE ANALYSIS {#app:prop-female}
## Introduction
The two-sex model requires a proportion of females as an input. In the Gulf of Alaska, observer length frequencies were used to determine that the stock is approximately 70% female (@goa2021). In `r bc`, both commercial fishery and synoptic survey data were used to determine the proportion female. This appendix descibes the weighting algorithm used, which is the same as what was used in @grandin2017 and based on the methods applied in @holt2016. The analysis here is based on aggregated area data for a coastwide stock.

## Data Selection
Both commercial and synoptic sample age data were filtered for input into the proportion female routine.

**Commercial trawl fishery**

The following three attributes were used to filter the age data for the commercial trawl fishery:

1. Species category
   a. Included codes:
      i. Unsorted
      i. Discards
   b. Rejected codes:
      i. Unknown
      i. Sorted
      i. Keepers
      i. Longline
2. Sample type
   a. Included codes:
      i. Total catch
      i. Random
      i. Random from randomly assigned set
      i. Random from set after randomly assigned set
      i. Random from set requested by vessel master
   b. Rejected codes
      i. Selected (various codes)
      i. Stratified
      i. Unknown sample for NMFS Triennial survey
3. Gear code
   a. Included codes:
      i. Bottom trawl
      i. Unknown trawl
   b. Rejected codes
      i. Unknown
      i. Trap
      i. Gillnet
      i. Handline
      i. Longline
      i. Midwater trawl
      i. Troll
      i. Seine
      i. Jig
      i. Recreational
      i. Various other obscure catch methods

**Synoptic surveys**
All available age data from the synoptic surveys were used.

**Years**
Age data from 1996 to 2019 were used. There was no age data available after 2019.

**Quarters of the year**
1 = January 1 - March 31
2 = April 1 - June 30
3 = July 1 - September 30
4 = October 1 - December 31

**Areas**
Coastwide, defined as areas 3CD and 5ABCDE aggregated.

**Sex**
Males and females only. Some records have the sex recorded as unknown or unsexed. Those records along with records with NULL sex were removed.
## Commercial Trawl Fishery
Observations within a sample are likely to be correlated due to the small area which is trawled in a single fishing event. In addition, trip samples may be correlated due to single vessel fishing practices. This algorithm calculates a sex-specifc mean weight by trip, calculated from individual sex-specific length observations converted to weight using Eq. \@ref(eq:specimen-wt), then uses Eqs. \@ref(eq:sample-wt)-–\@ref(eq:prop-female) to estimate proportion of females.

## Synoptic Surveys
For surveys,the same algorithm is followed except that the quarter of the year is not included in the calculation. This is because the surveys are single events which occur during the summer months only.
")
```

```{r appendix-prop-para-1-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("# ANALYSE DE LA PROPORTION FÉMININE {#app:prop-female}
## Introduction
Le modèle two-sex nécessite une proportion de femelles comme donnée d'entrée. Dans le Golfe de l'Alaska, les fréquences de longueur des observateurs ont été utilisées pour déterminer que le stock est composé d'environ 70% de femelles (@goa2021). En `r bc`, les données de la pêche commerciale et des relevés synoptiques ont été utilisées pour déterminer la proportion de femelles. Cette annexe décrit l'algorithme de pondération utilisé, qui est le même que celui utilisé dans @grandin2017 et basé sur les méthodes appliquées dans @holt2016. L'analyse ici est basée sur des données de zone agrégées pour un stock à l'échelle de la côte.

## Sélection des données
Les données d'âge des échantillons commerciaux et synoptiques ont été filtrées pour être introduites dans la routine de proportion de femelles.

**Pêche commerciale au chalut**

Les trois attributs suivants ont été utilisés pour filtrer les données d'âge pour la pêche commerciale au chalut :

1. Catégorie d'espèces
   a. Codes inclus :
      i. Non triés
      i. Rejets
   b. Codes rejetés :
      i. Inconnu
      i. Trié
      i. Gardiens
      i. Palangre
2. Type d'échantillon
   a. Codes inclus :
      i. Capture totale
      i. Aléatoire
      i. Aléatoire à partir d'un ensemble attribué aléatoirement
      i. Aléatoire à partir de l'ensemble après l'ensemble attribué aléatoirement
      i. Aléatoire à partir de l'ensemble demandé par le capitaine du navire
   b. Codes rejetés
      i. Sélectionnés (divers codes)
      i. Stratifié
      i. Échantillon inconnu pour l'enquête triennale du NMFS
3. Code de l'engin
   a. Codes inclus :
      i. Chalut de fond
      i. Chalut inconnu
   b. Codes rejetés
      i. Inconnu
      i. Piège
      i. Filet maillant
      i. Ligne à main
      i. Palangre
      i. Chalut pélagique
      i. Traîne
      i. Senne
      i. turlutte
      i. Récréatif
      i. Diverses autres méthodes de capture obscures

**Enquêtes synoptiques
Toutes les données disponibles sur l'âge provenant des enquêtes synoptiques ont été utilisées.

**Années**
Les données d'âge de 1996 à 2019 ont été utilisées. Aucune donnée d'âge n'était disponible après 2019.

**Trimestres de l'année
1 = 1er janvier - 31 mars
2 = 1er avril - 30 juin
3 = 1er juillet - 30 septembre
4 = 1er octobre - 31 décembre

**Zones**
Toute la côte, définie comme les zones 3CD et 5ABCDE agrégées.

**Sexe
Mâles et femelles uniquement. Le sexe de certains enregistrements est inconnu ou non sexé. Ces enregistrements ainsi que ceux dont le sexe est NUL ont été supprimés.
## Pêche commerciale au chalut
Les observations au sein d'un échantillon sont susceptibles d'être corrélées en raison de la petite zone qui est chalutée lors d'un seul événement de pêche. En outre, les échantillons de sorties peuvent être corrélés en raison des pratiques de pêche d'un seul navire. Cet algorithme calcule un poids moyen par sortie spécifique au sexe, calculé à partir des observations de longueur spécifiques au sexe individuelles converties en poids à l'aide de l'Eq. \@ref(eq:specimen-wt), puis utilise les Eqs. \@ref(eq:sample-wt)--\@ref(eq:prop-female) pour estimer la proportion de femelles.

## Enquêtes synoptiques
Pour les enquêtes, le même algorithme est suivi, sauf que le trimestre de l'année n'est pas inclus dans le calcul. Cela s'explique par le fait que les enquêtes sont des événements uniques qui se déroulent uniquement pendant les mois d'été.
")
```

```{r appendix-prop-equations-en, eval = !fr(), results = 'asis'}
cat("## EQUATIONS
Specimens without weight data but with length data have their weights calculated as follows:
\begin{equation}
\hat{w}_{i,j,s} = \alpha_s l_{i,j,s}^{\beta_s}
(\#eq:specimen-wt)
\end{equation}
where $\alpha_s$ and $\beta_s$ are parameters for sex $s$ and $w_{i,j,s}$ and $l_{i,j,s}$ are paired length-weight observations for specimen $i$ in sample $j$.

Total weight for each sample is the sum of the specimens in the sample:
\begin{equation}
W_{j,s,t} = \sum_{i=1}^{N_{j,s,t}}{\hat{w}_{i,j,s,t}}
(\#eq:sample-wt)
\end{equation}
where $W_{j,s,t}$ is the total weight for sample $j$, sex $s$, trip $t$, and $N_{j,s,t}$ is the number of specimens in sample $j$ for sex $s$.

Calculation of the mean sample weight by trip and sex is given by:
\begin{equation}
W_{s,t} = \frac{\sum\limits_{j=1}^{K_t}{W_{j,s,t}S_{j,t}}}{\sum\limits_{j=1}^{K_t}{S_{j,t}}}
(\#eq:mean-sample-wt)
\end{equation}
where $W_{s,t}$ is the mean weight for sex $s$ and trip $t$, weighted by sample weight, where $K_t$ is the number of samples in trip $t$, and $S_{j,t}$ is the sample weight for sample $j$ from trip $t$.

To calculate the total catch weight for sampled hauls in each trip, we use the following:
\begin{equation}
C_t = \sum_{j=1}^{K_t}{C_{j,t}}
(\#eq:catch-wt)
\end{equation}
where $C_t$ is the total catch weight for sampled hauls for trip $t$, $K_t$ is the number of samples in trip $t$, and $C_{j,t}$ is the catch weight associated with sample $j$ and trip $t$.

The total weight in each quarter of the year by sex is given by:
\begin{equation}
W_{q,s} = \frac{\sum\limits_{t=1}^{T_q}{W_{q,s,t}R_{q,t}}}{\sum\limits_{t=1}^{T_q}{R_{q,t}}}
(\#eq:quarter-wt)
\end{equation}
where $W_{q,s}$ is the total weight for sex $s$ and quarter of year $q$, $R_{q,t}$ is the trip weight for all sampled trips in quarter $q$, and $T_q$ is the number of sampled trips in quarter $q$.

The total catch weight for sampled hauls per quarter of the year is:
\begin{equation}
C_q = \sum_{t=1}^{K_q}{C_t}
(\#eq:total-catch-quarter)
\end{equation}
where $C_q$ is the total catch weight for sampled hauls for quarter $q$, $K_q$ is the number of trips in quarter $q$, and $C_t$ is the catch weight associated with trip $t$.

Now, the total weight by year and sex is calculated from:
\begin{equation}
W_{y,s} = \frac{\sum\limits_{q=1}^{4}{W_{q,y,s}C_{q,y}}}{\sum\limits_{q=1}^{4}{C_{q,y}}}
(\#eq:total-catch-year)
\end{equation}
where $W_{s,y}$ is the total weight for year $y$, sex $s$, $W_{q,y,s}$ is the weight in quarter $q$ of year $y$, and $C_{q,y}$ is the catch in quarter $q$ of year $y$.

Finally, the proportion female is given by:
\begin{equation}
P_y = \frac{W_{y,s=Female}}{W_{y,s=Male} + W_{y,s=Female}}
(\#eq:prop-female)
\end{equation}
where $P_y$ is the proportion female by weight for year $y$ and $W_{y,s}$ for $s=Female$ and $s=Male$ are given by Eq. \@ref(eq:total-catch-year).
")
```

```{r appendix-prop-equations-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## EQUATIONS
Les poids des spécimens sans données de poids mais avec des données de longueur sont calculés comme suit :
\begin{equation}
\hat{w}_{i,j,s} = \alpha_s l_{i,j,s}^{\beta_s}
(\#eq:specimen-wt)
\end{equation}
où $\alpha_s$ et $\beta_s$ sont des paramètres pour le sexe $s$ et $w_{i,j,s}$ et $l_{i,j,s}$ sont des observations appariées longueur-poids pour le spécimen $i$ dans l'échantillon $j$.

Le poids total pour chaque échantillon est la somme des spécimens de l'échantillon :
\begin{equation}
W_{j,s,t} = \sum_{i=1}^{N_{j,s,t}}{\hat{w}_{i,j,s,t}}
(\#eq:sample-wt)
\end{equation}
où $W_{j,s,t}$ est le poids total pour l'échantillon $j$, le sexe $s$, le voyage $t$, et $N_{j,s,t}$ est le nombre de spécimens dans l'échantillon $j$ pour le sexe $s$.

Le calcul du poids moyen de l'échantillon par sortie et par sexe est donné par la formule suivante :
\begin{equation}
W_{s,t} = \frac{\sum\limits_{j=1}^{K_t}{W_{j,s,t}S_{j,t}}}{\sum\limits_{j=1}^{K_t}{S_{j,t}}}
(\#eq:mean-sample-wt)
\end{equation}
où $W_{s,t}$ est le poids moyen pour le sexe $s$ et le voyage $t$, pondéré par le poids de l'échantillon, où $K_t$ est le nombre d'échantillons dans le voyage $t$, et $S_{j,t}$ est le poids de l'échantillon pour l'échantillon $j$ du voyage $t$.

Pour calculer le poids total des captures pour les traits échantillonnés au cours de chaque sortie, nous utilisons la formule suivante :
\begin{equation}
C_t = \sum_{j=1}^{K_t}{C_{j,t}}
(\#eq:catch-wt)
\end{equation}
où $C_t$ est le poids total de la capture pour les traits échantillonnés pour le voyage $t$, $K_t$ est le nombre d'échantillons dans le voyage $t$, et $C_{j,t}$ est le poids de la capture associé à l'échantillon $j$ et au voyage $t$.

Le poids total de chaque trimestre de l'année par sexe est donné par :
\begin{equation}
W_{q,s} = \frac{\sum\limits_{t=1}^{T_q}{W_{q,s,t}R_{q,t}}}{\sum\limits_{t=1}^{T_q}{R_{q,t}}}
(\#eq:quarter-wt)
\end{equation}
où $W_{q,s}$ est le poids total pour le sexe $s$ et le trimestre de l'année $q$, $R_{q,t}$ est le poids de la sortie pour toutes les sorties échantillonnées au cours du trimestre $q$, et $T_q$ est le nombre de sorties échantillonnées au cours du trimestre $q$.

Le poids total des captures pour les traits échantillonnés par trimestre de l'année est le suivant :
\begin{equation}
C_q = \sum_{t=1}^{K_q}{C_t}
(\#eq:total-catch-quarter)
\end{equation}
où $C_q$ est le poids total des captures pour les traits échantillonnés pour le trimestre $q$, $K_q$ est le nombre de sorties au cours du trimestre $q$, et $C_t$ est le poids des captures associé à la sortie $t$.

Maintenant, le poids total par année et par sexe est calculé à partir de :
\begin{equation}
W_{y,s} = \frac{\sum\limits_{q=1}^{4}{W_{q,y,s}C_{q,y}}}{\sum\limits_{q=1}^{4}{C_{q,y}}}
(\#eq:total-catch-year)
\end{equation}
où $W_{s,y}$ est le poids total pour l'année $y$, sexe $s$, $W_{q,y,s}$ est le poids au cours du trimestre $q$ de l'année $y$, et $C_{q,y}$ est la prise au cours du trimestre $q$ de l'année $y$.

Enfin, la proportion de femelles est donnée par
\begin{equation}
P_y = \frac{W_{y,s=Femelle}}{W_{y,s=Mâle} + W_{y,s=Femelle}}
(\#eq:prop-female)
\end{equation}
où $P_y$ est la proportion de femelles en poids pour l'année $y$ et $W_{y,s}$ pour $s$ = Femelle et $s$ = Mâle sont donnés par l'Eq. \@ref(eq:total-catch-year).
")
```

```{r appendix-prop-results-en, eval = !fr(), results = 'asis'}
cat("## Results
Table \@ref(tab:prop-female-table) shows the proportions female for the commercial trawl fishery and the four synoptic surveys. The means of all the years included in the table are shown in the last row. There is very good agreement between the survey and commercial mean proportions and therefore it is reasonable to take the mean of the means to arrive at a single value for overall proportion of females in the `r sp` stock in `r bc`. The mean of the means for the synoptic surveys and the commercial fishery is `r total_prop_female`. That is the proportion used as an input to all models (base, bridging, sensitivities, and retrospectives) in this assessment.

Tables \@ref(tab:prop-female-comm-weights-table) and \@ref(tab:prop-female-surv-weights-table) give a summary of the data used for the proportion female calculations. In most years there is a large number of weights included.
")
```

```{r appendix-prop-results-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("## Résultats
Le tableau \@ref(tab:prop-female-table) montre les proportions de femelles pour la pêche commerciale au chalut et les quatre enquêtes synoptiques. Les moyennes de toutes les années incluses dans le tableau sont indiquées dans la dernière ligne. Il existe une très bonne concordance entre les proportions moyennes des campagnes et celles de la pêche commerciale et il est donc raisonnable de prendre la moyenne des moyennes pour obtenir une valeur unique pour la proportion globale de femelles dans le stock `r sp` en `r bc`. La moyenne des moyennes pour les enquêtes synoptiques et la pêche commerciale est `r total_prop_female`. Il s'agit de la proportion utilisée comme entrée dans tous les modèles (de base, de transition, de sensibilité et rétrospectifs) de la présente évaluation.

Les tableaux \@ref(tab:prop-female-comm-weights-table) et \@ref(tab:prop-female-surv-weights-table) donnent un résumé des données utilisées pour les calculs de la proportion de femelles. Pour la plupart des années, un grand nombre de poids sont inclus.
")
```

```{r prop-female-table, results = "asis"}

cap <- paste0("Proportion of female ", sp, " in the commercial trawl fishery and four synoptic surveys coastwide. The survey acronyms stand for QCS = ", qcs, ", HS = ", hss, ", WCVI = ", wcvis, " and WCHG = ", wchgs, ".")
              
if(fr()){
  cap <- paste0("Proportion de femelles ", sp, " dans la pêche commerciale au chalut et dans quatre enquêtes synoptiques sur l'ensemble de la côte. Les acronymes des enquêtes sont ", tr("QCS"), " = ", qcs, ", ", tr("HS"), " = ", hss, ", ", tr("WCVI"), " = ", wcvis, " et ", tr("WCHG"), " = ", wchgs, ".")
}

table_prop_female(prop_female_lst, digits = 2, caption = cap)

```

```{r prop-female-comm-weights-table, results = "asis"}
cap <- paste0("Summary of samples and weights used for the calculation of proportion of female ", sp, " in the commercial trawl fishery.")
if(fr()){
  cap <- paste0("Résumé des échantillons et des poids utilisés pour le calcul de la proportion de femelles ", sp, " dans la pêche commerciale au chalut.")
}
table_prop_female_weights(dat$commercial_samples,
                          end_yr = 2019,
                          caption = cap,
                          col_widths = "5em")
```

```{r prop-female-surv-weights-table, results = "asis"}
cap <- paste0("Summary of samples and weights used for the calculation of proportion of female ", sp, " in the synoptic surveys. See Table \\ref{tab:prop-female-table} for survey acronym meanings.")
if(fr()){
  cap <- paste0("Résumé des échantillons et des poids utilisés pour le calcul de la proportion de femmes ", sp, " dans les enquêtes synoptiques. Voir le tableau \ref{tab:prop-female-table} pour la signification des acronymes des enquêtes.")
}
table_prop_female_weights(dat$survey_samples,
                          type = "survey",
                          end_yr = 2019, 
                          caption = cap,
                          col_widths = "5em")
```
