\clearpage

```{r app-eco-para-1-en, eval = !fr(), results = 'asis'}
cat("# ECOSYSTEM CONSIDERATIONS {#app:eco}
`r sp` are habitat and prey generalists [@fargo1981; @yang1993; @doyle2018]. However, we report diet composition from Alaska, because no diet data are collected on any of the surveys used in this assessment. Based on almost `r f(2000)` stomachs collected in the early 1990s in the GOA, `r  sp` consumed a diet dominated by zooplankton, fish, and benthic invertebrates [@yang1993; @goa2019]. For juveniles (<= 20 cm TL), euphausiids made up nearly 60% of their diet, followed by capelin at 24%. Adults consumed mostly capelin (*Mallotus villosus*), euphausiids, adult and juvenile Walleye Pollock (*Gadus chalcogrammus*), Pandalid shrimp, herring, and other forage fish, none of which account for more than 22% of the overall diet. In the same region and time period, predation by Pacific Cod (*Gadus macrocephalus*), Pacific Halibut (*Hippoglossus stenolepis*), and Steller sea lions (*Eumetopias jubatus*) together explained about 10% of adult arrowtooth mortality and the flatfish trawl fishery accounted for 2% [@goa2019]. Juvenile `r  sp` mortality was caused by adult `r  sp`, and both adult and juvenile pollock, but the total of these mortality sources is less than 7% of juvenile `r sp` production [@goa2019].

")
```

```{r app-eco-para-1-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("# CONSIDÉRATIONS ÉCOSYSTÉMIQUES {#app:eco}
`r sp` sont des généralistes de l'habitat et des proies [@fargo1981; @yang1993; @doyle2018]. Cependant, nous rapportons la composition du régime alimentaire de l'Alaska, car aucune donnée sur le régime alimentaire n'est collectée dans le cadre des enquêtes utilisées dans cette évaluation. D'après les estomacs de presque `r f(2000)` collectés au début des années 1990 dans la GOA, `r sp` avait un régime alimentaire dominé par le zooplancton, les poissons et les invertébrés benthiques [@yang1993; @goa2019]. Pour les juvéniles (<= 20 cm TL), les euphausiacés représentaient près de 60% de leur régime alimentaire, suivis par le capelan à 24%. Les adultes consommaient principalement du capelan (*Mallotus villosus*), des euphausiacés, des dorés jaunes adultes et juvéniles (*Gadus chalcogrammus*), des crevettes pandalides, des harengs et d'autres poissons fourrages, dont aucun ne représente plus de 22 % du régime alimentaire global. Dans la même région et à la même période, la prédation par la morue du Pacifique (*Gadus macrocephalus*), le flétan du Pacifique (*Hippoglossus stenolepis*) et les otaries de Steller (*Eumetopias jubatus*) expliquent ensemble environ 10 % de la mortalité des adultes et la pêche au chalut des poissons plats représente 2 % [@goa2019]. La mortalité des juvéniles de `r sp` a été causée par les `r sp` adultes et le colin adulte et juvénile, mais le total de ces sources de mortalité représente moins de 7 % de la production de `r sp` juvéniles [@goa2019].

")
```

```{r app-eco-para-2-en, eval = !fr(), results = 'asis'}
cat("Migration patterns are not well known for `r sp`, but there is some indication that larger fish may migrate to deeper water in winter and shallower water in summer [@arf1995; @arf2001]. Spawning and hatching occur in these deeper waters (> 350 m) along the continental shelf break in fall and winter [@arf1995; @blood2007]. At these depths, predation risk is relatively low, and cold temperatures along with intrinsically low metabolic rates ensure extended availability of yolk reserves, lowering the risk of larval starvation [@doyle2018]. Larval duration and drift is protracted, contributing to widespread delivery of larvae to coastal, continental shelf and slope waters and resulting in low connectivity between spawning and settlement areas [@doyle2018]. In the GOA, the smallest fish (< 10 cm) were typically found shallower than 200 m with all immature fish (< 30 cm) concentrating at < 400 m. In colder years, these size classes tended to be found deeper. In contrast, mature fish (30--60 cm) tended to be found deepest (> 800 m) in warmer years [@doyle2018]. A preliminary climate-related vulnerability assessment for GOA indicated low risk, high resilience overall; however, there exists some potential stage-specific sensitivity to temporal mis-match between larvae and zooplankton prey with increased temperatures [@doyle2018]. 

")
```

```{r app-eco-para-2-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("Les schémas de migration ne sont pas bien connus pour `r sp`, mais il y a des indications que les plus gros poissons peuvent migrer vers des eaux plus profondes en hiver et des eaux moins profondes en été [@arf1995; @arf2001]. Le frai et l'éclosion ont lieu dans ces eaux plus profondes (> 350 m) le long du rebord du plateau continental en automne et en hiver [@arf1995; @blood2007]. À ces profondeurs, le risque de prédation est relativement faible, et les températures froides ainsi que les taux métaboliques intrinsèquement bas assurent une disponibilité prolongée des réserves vitellines, ce qui réduit le risque de famine des larves [@doyle2018]. La durée et la dérive des larves sont prolongées, ce qui contribue à une livraison étendue des larves dans les eaux côtières, du plateau continental et du talus, et se traduit par une faible connectivité entre les zones de frai et de peuplement [@doyle2018]. Dans le GOA, les plus petits poissons (< 10 cm) se trouvaient généralement à moins de 200 m de profondeur, tous les poissons immatures (< 30 cm) se concentrant à < 400 m. Au cours des années plus froides, ces classes de taille avaient tendance à se trouver plus en profondeur. En revanche, les poissons matures (30-60 cm) avaient tendance à se trouver plus profondément (> 800 m) au cours des années plus chaudes [@doyle2018]. Une évaluation préliminaire de la vulnérabilité liée au climat pour la GOA a indiqué un risque faible, une résilience élevée dans l'ensemble; cependant, il existe une certaine sensibilité potentielle spécifique au stade à l'inadéquation temporelle entre les larves et les proies zooplanctoniques avec l'augmentation des températures [@doyle2018]. 

")
```

```{r app-eco-para-3-en, eval = !fr(), results = 'asis'}
cat("Within Canadian Pacific waters, a lack of correlation between change in abundance and changes in condition suggests that bottom-up ecosystem effects are unlikely to be driving overall stock status for `r  sp`. Coastwide within Canada, the condition index dropped steadily between 2004 and 2012 (Fig. \@ref(fig:condition-index)), while the survey biomass index for the same area increased by over 50% (Fig. \@ref(fig:geo-indexes-cpue)). Likewise, a sharp increase in condition index in 2015 has not been associated with any positive trajectories in biomass in the following 7 years.

")
```

```{r app-eco-para-3-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("Dans les eaux canadiennes du Pacifique, l'absence de corrélation entre les changements d'abondance et les changements de condition suggère qu'il est peu probable que les effets écosystémiques ascendants soient à l'origine de l'état général du stock de `r sp`. Sur l'ensemble de la côte canadienne, l'indice de condition a chuté régulièrement entre 2004 et 2012 (Fig. \@ref(fig:condition-index)), alors que l'indice de biomasse de l'étude pour la même zone a augmenté de plus de 50 % (Fig. \@ref(fig:geo-indexes-cpue)). De même, une forte augmentation de l'indice de condition en 2015 n'a pas été associée à des trajectoires positives de la biomasse au cours des 7 années suivantes.

")
```

```{r app-eco-para-4-en, eval = !fr(), results = 'asis'}
cat("The evidence that condition tends to be higher in deeper, and therefore cooler, waters is consistent with findings of some potential sensitivity to temperature [@english2021]. Local warming (positive temperature velocity) was associated with declines in biomass only in already warmer areas, and associated with increases biomass of immatures (~ 38 cm for females, ~ 31 cm for males) in cooler areas. However, when the shape of depth effect on condition was allowed to vary between year, there was not an obvious difference between warmer and cooler years (Fig. \@ref(fig:condition-tv)). If there is any weak association, it might be that condition is higher in shallower waters in the warmer year, which is consistent with the coastwide condition index also climbing steeply between 2013 and 2015, the period that includes the 2014--2016 marine heat wave and spikes in the abundances of some more southern species of euphausiid [@boldt2021]. In contrast, mean body condition in the GOA was low during the marine heat wave (2015) and even lower in 2017 [@goa2019]. This was hypothesized to be due to both increased energetic demands with warm temperatures and lack of forage fish prey. Marine heat wave conditions occurred again in the Northeast Pacific in 2018, and 2019--2020, although they were not as extreme as in 2014--2016 [@boldt2021].

Of what are presumed to be the dominant natural predators (based on data from Alaska [@goa2019]) few appear likely to cause the declines in `r sp` spawning biomass since 2011 (Figure \@ref(fig:fig-base-sb)). Walleye Pollock, predators of juvenile `r sp`, have experienced an overall increase in survey biomass punctuated by a shortterm declines that either coincided with (southern stock) or preceeded (northern stock) the downturn in `r sp`. Abundances of both Pacific Cod [@forrest2020pcod] and Pacific Halibut [@dfo2022synopsis] appear to have been relatively stable at the decadal scale, despite considerable interannual variability. Only Steller's Sea Lion have experienced a steady population growth rate of around 4.3% per year during the past two decades [@dfo2021sealion], but without any obvious changes in trajectory that could be associated with the changes in `r sp` spawning biomass.

")
```

```{r app-eco-para-4-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("La preuve que la condition tend à être plus élevée dans les eaux plus profondes, et donc plus fraîches, est cohérente avec les résultats d'une certaine sensibilité potentielle à la température [@english2021]. Le réchauffement local (vitesse de température positive) a été associé à des baisses de biomasse uniquement dans les zones déjà plus chaudes, et à des augmentations de la biomasse des immatures (~ 38 cm pour les femelles, ~ 31 cm pour les mâles) dans les zones plus froides. Cependant, lorsque la forme de l'effet de la profondeur sur la condition a été autorisée à varier d'une année à l'autre, il n'y avait pas de différence évidente entre les années plus chaudes et plus froides (Fig. \@ref(fig:condition-tv)). S'il existe une faible association, c'est peut-être parce que la condition est plus élevée dans les eaux moins profondes au cours de l'année la plus chaude, ce qui est cohérent avec le fait que l'indice de condition à l'échelle de la côte a également grimpé en flèche entre 2013 et 2015, période qui comprend la vague de chaleur marine de 2014-2016 et les pics d'abondance de certaines espèces d'euphausiacés plus méridionales [@boldt2021]. En revanche, la condition corporelle moyenne dans le GOA était faible pendant la vague de chaleur marine (2015) et encore plus faible en 2017 [@goa2019]. On a émis l'hypothèse que cela était dû à la fois à des exigences énergétiques accrues avec les températures chaudes et au manque de poissons fourrage. Des vagues de chaleur marine se sont à nouveau produites dans le Pacifique Nord-Est en 2018 et en 2019-2020, bien qu'elles n'aient pas été aussi extrêmes qu'en 2014-2016 [@boldt2021].

Parmi ce que l'on suppose être les prédateurs naturels dominants (sur la base des données de l'Alaska [@goa2019]), peu semblent susceptibles de causer les déclins de la biomasse de frai `r sp` depuis 2011 (Figure \@ref(fig:fig-base-sb)). Le doré jaune, prédateur des juvéniles de `r sp`, a connu une augmentation globale de la biomasse étudiée, ponctuée par un déclin à court terme qui a coïncidé (stock méridional) ou précédé (stock septentrional) le déclin de `r sp`. Les abondances du cabillaud du Pacifique [@forrest2020pcod] et du flétan du Pacifique [@dfo2022synopsis] semblent avoir été relativement stables à l'échelle décennale, malgré une variabilité interannuelle considérable. Seule l'otarie de Steller a connu un taux de croissance démographique régulier d'environ 4,3 % par an au cours des deux dernières décennies [@dfo2021sealion], mais sans aucun changement évident de trajectoire qui pourrait être associé aux changements de la biomasse reproductrice `r sp`.

")
```
