```{r app-comp-env-para-1-en, eval = !fr(), results = 'asis'}
cat("# COMPUTATIONAL ENVIRONMENT

The source code for this assessment can be found on GitHub, in several packages in the ````pbs-assess```` organization's repository list (Table \@ref(tab:table-env)).

This version of the document was generated on `r format(lubridate::as_date(Sys.time()), format = '%a %b %d, %Y')`
with `r devtools::session_info()$platform$version` [@r2022].

")
```

```{r app-comp-env-para-1-fr, eval = fr(), results = 'asis', needs_trans = FALSE}
cat("# ENVIRONNEMENT INFORMATIQUE

Le code source de cette évaluation est disponible sur GitHub, dans plusieurs paquets de la liste des dépôts de l'organisation ````pbs-assess```` (Tableau \@ref(tab:table-env)).

Cette version du document a été générée le `r format(lubridate::as_date(Sys.time()), format = '%a %b %d, %Y')`
avec `r devtools::session_info()$platform$version` [@r2022].
")
```

```{r table-env, echo = FALSE, results = 'asis'}

# Need to load sdmTMB here for it to show up in the packages list with version number
library(sdmTMB)
library(gfutilities)

pkgs <- list("arrowtooth",
             "bookdown", "broom",
             "csasdown",
             "devtools", "dplyr",
             "gfdata", "gfiscam", "gfiscamutils", "gfplot", "ggplot2", "glmmTMB", "gridExtra",
             "here",
             "kableExtra",
             "knitr",
             "purrr",
             "rmarkdown", "rosettafish",
             "sdmTMB",
             "tidylog", "TMB")

pkg_df <- tribble(~package, ~org,
                  "arrowtooth", "pbs-assess",
                  "bookdown", "rstudio",
                  "broom", "tidymodels",
                  "csasdown", "pbs-assess",
                  "devtools", "r-lib",
                  "dplyr", "tidyverse",
                  "gfdata", "pbs-assess",
                  "gfiscam", "pbs-assess",
                  "gfiscamutils", "pbs-assess",
                  "gfplot", "pbs-assess",
                  "ggplot2", "tidyverse",
                  "glmmTMB", "glmmTMB",
                  "gridExtra", "baptiste",
                  "here", "r-lib",
                  "kableExtra", "cgrandin (forked from haozhu233)",
                  "knitr", "yihui",
                  "purrr", "tidyverse",
                  "rmarkdown", "rstudio",
                  "rosettafish", "pbs-assess",
                  "sdmTMB", "pbs-assess",
                  "tidylog", "elbersb",
                  "TMB", "kaskr/adcomp")

# Get the current commit of the gfiscam repository
sha <- system2("git", "-C ~/github/pbs-assess/gfiscam rev-parse HEAD", wait = TRUE, stdout = TRUE)

gfiscam_pkg <- vec2df(c("gfiscam", "pbs-assess", substr(sha, 1, 6)),
                      nms = c("package", "org", "loadedversion"))

cap <- paste0("The packages, their associated GitHub organizations and package versions used for this assessment. All are R packages except for ````gfiscam```` which is an ADMB/C++ package containing the ", iscam, " implementation used in this assessment. The 'Package Version' given for ````gfiscam```` is the commit SHA on GitHub. The 'Package Version' for the R packages are what is returned when running the ````session_info()$packages```` command in R.")
if(fr()){
  cap <- paste0("Les paquets, leurs organisations GitHub associées et les versions des paquets utilisés pour cette évaluation. Tous les paquets sont des paquets R, à l'exception de ````gfiscam```` qui est un paquet ADMB/C++ contenant l'implémentation ", iscam, "utilisée dans cette évaluation. La « Package Version » donnée pour ````gfiscam```` est le commit SHA sur GitHub. La « Version du paquet » pour les paquets R est celle qui est renvoyée lors de l'exécution de la commande ````session_info()$packages```` dans R.")
}
info <- session_info()$packages |> 
  as.data.frame() |> 
  as_tibble() |> 
  select(package, loadedversion) |> 
  filter(package %in% pkgs) |> 
  left_join(pkg_df, by = "package") |>
  select(package, org, loadedversion) |> 
  bind_rows(gfiscam_pkg) |> 
  setNames(c(
    ifelse(fr(),
           "Paquet/Dépôt",
           "Package/Repository"),
    ifelse(fr(),
           "Utilisateur GitHub/Organisation",
           "GitHub User/Organization"),
    ifelse(fr(),
           "Version du paquet",
           "Package Version"))) |>
  csas_table(cap = cap)

info
```
